-- Green Button analytics rewire (duplicate-safe)
-- Creates/rewires analytics views and materialized views WITHOUT populating data.
-- No REFRESH MATERIALIZED VIEW statements are included in this script.

create or replace view public.green_button_intervals_analytics_v as
select *
from public.green_button_intervals
where coalesce(is_duplicate, false) = false
  and coalesce(stream_role, 'other') in ('consumption', 'other')
  and value_wh is not null;

create or replace view public.green_button_kpi_guardrail_v as
with stream_points as (
  select
    org_id,
    building_id,
    interval_start_utc,
    canonical_stream_id,
    sum(value_wh)::numeric(18,6) as stream_value_wh,
    sum(value_wh) / 1000.0 as stream_kwh,
    sum((value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0)::numeric(18,6) as stream_kw
  from public.green_button_intervals_analytics_v
  group by org_id, building_id, interval_start_utc, canonical_stream_id
),
building_points as (
  select
    org_id,
    building_id,
    interval_start_utc,
    sum(stream_value_wh)::numeric(18,6) as building_value_wh,
    sum(stream_kwh)::numeric(18,6) as building_kwh,
    sum(stream_kw)::numeric(18,6) as building_kw,
    count(*)::integer as canonical_stream_count
  from stream_points
  group by org_id, building_id, interval_start_utc
)
select
  s.org_id,
  s.building_id,
  s.interval_start_utc,
  s.canonical_stream_id,
  s.stream_value_wh,
  s.stream_kwh,
  s.stream_kw,
  b.building_value_wh,
  b.building_kwh,
  b.building_kw,
  b.canonical_stream_count
from stream_points s
join building_points b
  on b.org_id = s.org_id
 and b.building_id = s.building_id
 and b.interval_start_utc = s.interval_start_utc;

create or replace view public.green_button_intervals_hourly as
select
  org_id,
  building_id,
  date_trunc('hour', interval_start_utc) as hour_start_utc,
  sum(value_wh) / 1000.0 as kwh
from public.green_button_intervals_analytics_v
group by org_id, building_id, date_trunc('hour', interval_start_utc);

do $do$
declare
  obj text;
begin
  for obj in
    select unnest(array[
      'green_button_monthly_energy_mv',
      'green_button_monthly_top_peaks_mv',
      'green_button_startup_intensity_monthly_mv',
      'green_button_peak_timing_monthly_mv',
      'green_button_after_hours_load_monthly_mv',
      'green_button_after_hours_pct_monthly_mv',
      'green_button_load_shape_monthly_mv',
      'green_button_weekend_ops_monthly_mv',
      'green_button_demand_facts_monthly_mv'
    ]::text[])
  loop
    if exists (
      select 1
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public'
        and c.relname = obj
        and c.relkind = 'm'
    ) then
      execute format('drop materialized view public.%I', obj);
    elsif exists (
      select 1
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public'
        and c.relname = obj
        and c.relkind = 'v'
    ) then
      execute format('drop view public.%I', obj);
    end if;
  end loop;
end
$do$;


create table if not exists public.green_button_monthly_energy_history (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  month_start date not null,
  kwh_total numeric(18,6) not null check (kwh_total >= 0),
  source text not null default 'archived',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint green_button_monthly_energy_history_unique
    unique (org_id, building_id, month_start)
);

create index if not exists green_button_monthly_energy_history_org_month_idx
  on public.green_button_monthly_energy_history (org_id, month_start desc);

create materialized view public.green_button_monthly_energy_mv as
with raw_monthly as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_utc)::date as month_start,
    sum(value_wh) / 1000.0 as kwh_total
  from public.green_button_intervals_analytics_v
  group by
    org_id,
    building_id,
    date_trunc('month', interval_start_utc)
),
combined as (
  select
    org_id,
    building_id,
    month_start,
    kwh_total,
    2 as source_rank
  from raw_monthly
  union all
  select
    org_id,
    building_id,
    month_start,
    kwh_total,
    1 as source_rank
  from public.green_button_monthly_energy_history
),
final_ranked as (
  select
    org_id,
    building_id,
    month_start,
    kwh_total,
    row_number() over (
      partition by org_id, building_id, month_start
      order by source_rank desc
    ) as rn
  from combined
)
select
  org_id,
  building_id,
  month_start,
  kwh_total,
  now() as refreshed_at
from final_ranked
where rn = 1
with no data;



create materialized view public.green_button_monthly_top_peaks_mv as
with raw_ranked as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_utc)::date as month_start,
    (value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0 as peak_kw,
    interval_start_utc as peak_interval_start_utc,
    row_number() over (
      partition by org_id, building_id, date_trunc('month', interval_start_utc)
      order by
        (value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0 desc,
        interval_start_utc desc
    ) as peak_rank
  from public.green_button_intervals_analytics_v
  where duration_seconds > 0
),
raw_top as (
  select
    org_id,
    building_id,
    month_start,
    peak_rank,
    peak_kw,
    peak_interval_start_utc,
    2 as source_rank
  from raw_ranked
  where peak_rank <= 5
),
history_top as (
  select
    org_id,
    building_id,
    month_start,
    peak_rank,
    peak_kw,
    peak_interval_start_utc,
    1 as source_rank
  from public.green_button_monthly_top_peaks_history
),
combined as (
  select * from raw_top
  union all
  select * from history_top
),
final_ranked as (
  select
    org_id,
    building_id,
    month_start,
    peak_rank,
    peak_kw,
    peak_interval_start_utc,
    row_number() over (
      partition by org_id, building_id, month_start, peak_rank
      order by source_rank desc
    ) as rn
  from combined
)
select
  org_id,
  building_id,
  month_start,
  peak_rank,
  peak_kw,
  peak_interval_start_utc
from final_ranked
where rn = 1
with no data;



create materialized view public.green_button_startup_intensity_monthly_mv as
with interval_points as (
  select
    org_id,
    building_id,
    interval_start_utc,
    interval_start_utc at time zone 'UTC' as interval_start_local,
    (value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0 as kw
  from public.green_button_intervals_analytics_v
  where duration_seconds > 0
),
ramp_points as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_local)::date as month_start,
    interval_start_utc as ramp_interval_start_utc,
    interval_start_local,
    kw - lag(kw) over (
      partition by org_id, building_id
      order by interval_start_utc
    ) as ramp_kw
  from interval_points
),
ranked as (
  select
    org_id,
    building_id,
    month_start,
    ramp_kw as max_ramp_kw,
    ramp_interval_start_utc,
    row_number() over (
      partition by org_id, building_id, month_start
      order by ramp_kw desc, ramp_interval_start_utc desc
    ) as rn
  from ramp_points
  where extract(hour from interval_start_local) >= 4
    and extract(hour from interval_start_local) < 9
    and ramp_kw is not null
    and ramp_kw > 0
),
raw_monthly as (
  select
    org_id,
    building_id,
    month_start,
    max_ramp_kw,
    ramp_interval_start_utc
  from ranked
  where rn = 1
),
combined as (
  select org_id, building_id, month_start, max_ramp_kw, ramp_interval_start_utc
  from raw_monthly
  union all
  select org_id, building_id, month_start, max_ramp_kw, ramp_interval_start_utc
  from public.green_button_startup_intensity_monthly_history
),
final_ranked as (
  select
    org_id,
    building_id,
    month_start,
    max_ramp_kw,
    ramp_interval_start_utc,
    row_number() over (
      partition by org_id, building_id, month_start
      order by max_ramp_kw desc, ramp_interval_start_utc desc nulls last
    ) as rn
  from combined
)
select
  org_id,
  building_id,
  month_start,
  max_ramp_kw,
  ramp_interval_start_utc
from final_ranked
where rn = 1
with no data;



create materialized view public.green_button_peak_timing_monthly_mv as
with interval_points as (
  select
    org_id,
    building_id,
    interval_start_utc,
    interval_start_utc at time zone 'UTC' as interval_start_local,
    (value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0 as kw
  from public.green_button_intervals_analytics_v
  where duration_seconds > 0
),
daily_ranked as (
  select
    org_id,
    building_id,
    date(interval_start_local) as local_day,
    date_trunc('month', interval_start_local)::date as month_start,
    extract(hour from interval_start_local)::integer as peak_hour_local,
    row_number() over (
      partition by org_id, building_id, date(interval_start_local)
      order by kw desc, interval_start_utc desc
    ) as rn
  from interval_points
),
raw_histogram as (
  select
    org_id,
    building_id,
    month_start,
    peak_hour_local,
    count(*)::integer as daily_peak_count
  from daily_ranked
  where rn = 1
  group by org_id, building_id, month_start, peak_hour_local
),
combined as (
  select org_id, building_id, month_start, peak_hour_local, daily_peak_count
  from raw_histogram
  union all
  select org_id, building_id, month_start, peak_hour_local, daily_peak_count
  from public.green_button_peak_timing_monthly_history
),
final_rows as (
  select
    org_id,
    building_id,
    month_start,
    peak_hour_local,
    sum(daily_peak_count)::integer as daily_peak_count
  from combined
  group by org_id, building_id, month_start, peak_hour_local
)
select
  org_id,
  building_id,
  month_start,
  peak_hour_local,
  daily_peak_count
from final_rows
with no data;



create materialized view public.green_button_after_hours_load_monthly_mv as
with interval_points as (
  select
    org_id,
    building_id,
    interval_start_utc,
    interval_start_utc at time zone 'UTC' as interval_start_local,
    (value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0 as kw
  from public.green_button_intervals_analytics_v
  where duration_seconds > 0
),
night_points as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_local)::date as month_start,
    date(interval_start_local) as local_day,
    kw,
    interval_start_utc
  from interval_points
  where extract(hour from interval_start_local) >= 22
     or extract(hour from interval_start_local) < 4
),
daily_mins as (
  select
    org_id,
    building_id,
    month_start,
    local_day,
    kw as night_min_kw,
    row_number() over (
      partition by org_id, building_id, local_day
      order by kw asc, interval_start_utc desc
    ) as rn
  from night_points
  where kw > 0
),
raw_monthly as (
  select
    org_id,
    building_id,
    month_start,
    avg(night_min_kw)::numeric(18,6) as avg_night_min_kw,
    count(*)::integer as nights_count
  from daily_mins
  where rn = 1
  group by org_id, building_id, month_start
),
combined as (
  select
    org_id,
    building_id,
    month_start,
    avg_night_min_kw,
    nights_count,
    2 as source_rank
  from raw_monthly
  union all
  select
    org_id,
    building_id,
    month_start,
    avg_night_min_kw,
    nights_count,
    1 as source_rank
  from public.green_button_after_hours_load_monthly_history
),
final_ranked as (
  select
    org_id,
    building_id,
    month_start,
    avg_night_min_kw,
    nights_count,
    row_number() over (
      partition by org_id, building_id, month_start
      order by source_rank desc
    ) as rn
  from combined
)
select
  org_id,
  building_id,
  month_start,
  avg_night_min_kw,
  nights_count
from final_ranked
where rn = 1
with no data;



create materialized view public.green_button_after_hours_pct_monthly_mv as
with interval_points as (
  select
    org_id,
    building_id,
    interval_start_utc at time zone 'UTC' as interval_start_local,
    source_usage_point_id,
    (value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0 as kw
  from public.green_button_intervals_analytics_v
  where duration_seconds > 0
),
dedup_usage_point_interval as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_local)::date as month_start,
    date(interval_start_local) as local_day,
    interval_start_local,
    source_usage_point_id,
    max(kw)::numeric(18,6) as usage_point_kw
  from interval_points
  group by
    org_id,
    building_id,
    date_trunc('month', interval_start_local)::date,
    date(interval_start_local),
    interval_start_local,
    source_usage_point_id
),
building_interval as (
  select
    org_id,
    building_id,
    month_start,
    local_day,
    interval_start_local,
    extract(isodow from interval_start_local)::int as isodow,
    extract(hour from interval_start_local)::int as hour_local,
    extract(minute from interval_start_local)::int as minute_local,
    sum(usage_point_kw)::numeric(18,6) as building_kw
  from dedup_usage_point_interval
  group by org_id, building_id, month_start, local_day, interval_start_local
),
two_am_points as (
  select
    org_id,
    building_id,
    month_start,
    building_kw
  from building_interval
  where isodow between 1 and 5
    and hour_local = 2
    and minute_local = 0
),
daily_peaks as (
  select
    org_id,
    building_id,
    month_start,
    local_day,
    max(building_kw)::numeric(18,6) as daily_peak_kw
  from building_interval
  where isodow between 1 and 5
  group by org_id, building_id, month_start, local_day
),
two_am_agg as (
  select
    org_id,
    building_id,
    month_start,
    avg(building_kw)::numeric(18,6) as avg_2am_kw_weekdays,
    count(*)::integer as two_am_intervals_count
  from two_am_points
  group by org_id, building_id, month_start
),
daily_peak_agg as (
  select
    org_id,
    building_id,
    month_start,
    max(daily_peak_kw)::numeric(18,6) as peak_weekday_kw
  from daily_peaks
  group by org_id, building_id, month_start
)
select
  t.org_id,
  t.building_id,
  t.month_start,
  t.avg_2am_kw_weekdays,
  p.peak_weekday_kw,
  t.two_am_intervals_count
from two_am_agg t
join daily_peak_agg p
  on p.org_id = t.org_id
 and p.building_id = t.building_id
 and p.month_start = t.month_start
with no data;



create materialized view public.green_button_load_shape_monthly_mv as
with interval_points as (
  select
    i.org_id,
    i.building_id,
    i.interval_start_utc,
    i.interval_start_utc at time zone coalesce(
      nullif(to_jsonb(b) ->> 'timezone', ''),
      nullif(to_jsonb(b) ->> 'time_zone', ''),
      nullif(to_jsonb(b) ->> 'tz', ''),
      'America/Chicago'
    ) as interval_start_local,
    (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 as kw
  from public.green_button_intervals_analytics_v i
  left join public.buildings b
    on b.id = i.building_id
  where i.duration_seconds > 0
),
weekday_points as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_local)::date as month_start,
    date(interval_start_local) as local_day,
    extract(hour from interval_start_local)::integer as local_hour,
    floor(extract(minute from interval_start_local) / 15.0)::integer as quarter_hour,
    kw
  from interval_points
  where extract(isodow from interval_start_local) between 1 and 5
),
raw_monthly as (
  select
    org_id,
    building_id,
    month_start,
    (local_hour * 4 + quarter_hour)::smallint as slot_index,
    lpad(local_hour::text, 2, '0') || ':' || lpad((quarter_hour * 15)::text, 2, '0') as hhmm,
    avg(kw)::numeric(18,6) as avg_kw,
    count(*)::integer as intervals_count,
    count(distinct local_day)::integer as weekday_days_count
  from weekday_points
  where quarter_hour between 0 and 3
  group by org_id, building_id, month_start, local_hour, quarter_hour
),
combined as (
  select
    org_id,
    building_id,
    month_start,
    slot_index,
    hhmm,
    avg_kw,
    intervals_count,
    weekday_days_count,
    2 as source_rank
  from raw_monthly
  union all
  select
    org_id,
    building_id,
    month_start,
    slot_index,
    hhmm,
    avg_kw,
    intervals_count,
    weekday_days_count,
    1 as source_rank
  from public.green_button_load_shape_monthly_history
),
final_ranked as (
  select
    org_id,
    building_id,
    month_start,
    slot_index,
    hhmm,
    avg_kw,
    intervals_count,
    weekday_days_count,
    row_number() over (
      partition by org_id, building_id, month_start, slot_index
      order by source_rank desc
    ) as rn
  from combined
)
select
  org_id,
  building_id,
  month_start,
  slot_index,
  hhmm,
  avg_kw,
  intervals_count,
  weekday_days_count
from final_ranked
where rn = 1
with no data;



create materialized view public.green_button_weekend_ops_monthly_mv as
with interval_points as (
  select
    org_id,
    building_id,
    interval_start_utc at time zone 'UTC' as interval_start_local,
    value_wh / 1000.0 as kwh
  from public.green_button_intervals_analytics_v
  where duration_seconds > 0
),
daily_totals as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_local)::date as month_start,
    date(interval_start_local) as local_day,
    sum(kwh)::numeric(18,6) as day_kwh
  from interval_points
  group by org_id, building_id, date_trunc('month', interval_start_local), date(interval_start_local)
),
raw_monthly as (
  select
    org_id,
    building_id,
    month_start,
    avg(day_kwh) filter (where extract(isodow from local_day) in (6, 7))::numeric(18,6) as weekend_kwh_avg,
    avg(day_kwh) filter (where extract(isodow from local_day) between 1 and 5)::numeric(18,6) as weekday_kwh_avg,
    count(*) filter (where extract(isodow from local_day) in (6, 7))::integer as weekend_days_count,
    count(*) filter (where extract(isodow from local_day) between 1 and 5)::integer as weekday_days_count
  from daily_totals
  group by org_id, building_id, month_start
),
combined as (
  select
    org_id,
    building_id,
    month_start,
    weekend_kwh_avg,
    weekday_kwh_avg,
    weekend_days_count,
    weekday_days_count,
    2 as source_rank
  from raw_monthly
  union all
  select
    org_id,
    building_id,
    month_start,
    weekend_kwh_avg,
    weekday_kwh_avg,
    weekend_days_count,
    weekday_days_count,
    1 as source_rank
  from public.green_button_weekend_ops_monthly_history
),
final_ranked as (
  select
    org_id,
    building_id,
    month_start,
    weekend_kwh_avg,
    weekday_kwh_avg,
    weekend_days_count,
    weekday_days_count,
    row_number() over (
      partition by org_id, building_id, month_start
      order by source_rank desc
    ) as rn
  from combined
)
select
  org_id,
  building_id,
  month_start,
  weekend_kwh_avg,
  weekday_kwh_avg,
  weekend_days_count,
  weekday_days_count
from final_ranked
where rn = 1
with no data;



create materialized view public.green_button_demand_facts_monthly_mv as
with normalized as (
  select
    b.org_id,
    bm.building_id,
    date_trunc('month', bm.bill_month)::date as month_start,
    bm.adjusted_demand_kw,
    bm.tariff_min_kw,
    bm.ratchet_kw,
    bm.billing_demand_kw,
    bm.demand_charge_usd
  from public.bill_months bm
  join public.buildings b
    on b.id = bm.building_id
  where bm.bill_month is not null
    and bm.building_id is not null
),
aggregated as (
  select
    org_id,
    building_id,
    month_start,
    max(adjusted_demand_kw)::numeric(18,6) as adjusted_demand_kw,
    max(tariff_min_kw)::numeric(18,6) as tariff_min_kw,
    max(ratchet_kw)::numeric(18,6) as ratchet_kw,
    max(billing_demand_kw)::numeric(18,6) as billing_demand_kw,
    sum(demand_charge_usd)::numeric(18,6) as demand_charge_usd_total,
    sum(billing_demand_kw) filter (where billing_demand_kw > 0 and demand_charge_usd is not null)::numeric(18,6)
      as billing_demand_kw_for_rate
  from normalized
  group by org_id, building_id, month_start
)
select
  org_id,
  building_id,
  month_start,
  adjusted_demand_kw,
  tariff_min_kw,
  ratchet_kw,
  billing_demand_kw,
  demand_charge_usd_total,
  case
    when billing_demand_kw_for_rate > 0
      then (demand_charge_usd_total / billing_demand_kw_for_rate)::numeric(18,6)
    else null
  end as effective_demand_rate_usd_per_kw
from aggregated
with no data;




-- Recreate MV indexes
create unique index if not exists green_button_monthly_energy_mv_uidx
  on public.green_button_monthly_energy_mv (org_id, building_id, month_start);
create index if not exists green_button_monthly_energy_mv_org_month_idx
  on public.green_button_monthly_energy_mv (org_id, month_start desc);

create unique index if not exists green_button_monthly_top_peaks_mv_uidx
  on public.green_button_monthly_top_peaks_mv (org_id, building_id, month_start, peak_rank);
create index if not exists green_button_monthly_top_peaks_mv_org_month_idx
  on public.green_button_monthly_top_peaks_mv (org_id, month_start desc);

create unique index if not exists green_button_startup_intensity_monthly_mv_uidx
  on public.green_button_startup_intensity_monthly_mv (org_id, building_id, month_start);
create index if not exists green_button_startup_intensity_monthly_mv_org_month_idx
  on public.green_button_startup_intensity_monthly_mv (org_id, month_start desc);

create unique index if not exists green_button_peak_timing_monthly_mv_uidx
  on public.green_button_peak_timing_monthly_mv (org_id, building_id, month_start, peak_hour_local);
create index if not exists green_button_peak_timing_monthly_mv_org_month_idx
  on public.green_button_peak_timing_monthly_mv (org_id, month_start desc);

create unique index if not exists green_button_after_hours_load_monthly_mv_uidx
  on public.green_button_after_hours_load_monthly_mv (org_id, building_id, month_start);
create index if not exists green_button_after_hours_load_monthly_mv_org_month_idx
  on public.green_button_after_hours_load_monthly_mv (org_id, month_start desc);

create unique index if not exists green_button_after_hours_pct_monthly_mv_uidx
  on public.green_button_after_hours_pct_monthly_mv (org_id, building_id, month_start);
create index if not exists green_button_after_hours_pct_monthly_mv_org_month_idx
  on public.green_button_after_hours_pct_monthly_mv (org_id, month_start desc);

create unique index if not exists green_button_load_shape_monthly_mv_uidx
  on public.green_button_load_shape_monthly_mv (org_id, building_id, month_start, slot_index);
create index if not exists green_button_load_shape_monthly_mv_org_month_idx
  on public.green_button_load_shape_monthly_mv (org_id, month_start desc);

create unique index if not exists green_button_weekend_ops_monthly_mv_uidx
  on public.green_button_weekend_ops_monthly_mv (org_id, building_id, month_start);
create index if not exists green_button_weekend_ops_monthly_mv_org_month_idx
  on public.green_button_weekend_ops_monthly_mv (org_id, month_start desc);

create unique index if not exists green_button_demand_facts_monthly_mv_uidx
  on public.green_button_demand_facts_monthly_mv (org_id, building_id, month_start);
create index if not exists green_button_demand_facts_monthly_mv_org_month_idx
  on public.green_button_demand_facts_monthly_mv (org_id, month_start desc);





