-- Green Button interval analytics schema draft
-- Draft only. Review before applying to any environment.

-- 1) File-level import tracking
create table if not exists public.green_button_imports (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  uploaded_by uuid null references auth.users(id) on delete set null,

  source_utility text not null default 'evergy',
  source_filename text not null,
  file_checksum_sha256 text not null,
  source_meter_identifier text null,

  status text not null default 'uploaded'
    check (status in ('uploaded', 'parsed', 'loaded', 'failed')),

  interval_count_parsed integer not null default 0,
  interval_count_inserted integer not null default 0,
  interval_count_deduped integer not null default 0,
  interval_count_rejected integer not null default 0,
  interval_count_unmatched_meter integer not null default 0,

  error_summary jsonb not null default '{}'::jsonb,
  import_notes jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists green_button_imports_checksum_uidx
  on public.green_button_imports (org_id, file_checksum_sha256);

create index if not exists green_button_imports_org_status_idx
  on public.green_button_imports (org_id, status, created_at desc);


-- 2) Mapping from utility/source meter IDs to internal meters.id
create table if not exists public.green_button_meter_mappings (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  meter_id uuid not null references public.meters(id) on delete cascade,

  source_utility text not null default 'evergy',
  source_meter_identifier text not null,

  is_active boolean not null default true,
  mapping_notes jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint green_button_meter_map_unique
    unique (org_id, source_utility, source_meter_identifier)
);

create index if not exists green_button_meter_map_meter_idx
  on public.green_button_meter_mappings (meter_id, is_active);

-- Ingestion rule (application-level): intervals are loaded only when source meter
-- resolves to an existing public.meters.id (via mapping/direct match on meters.label).
-- If building context is available, matcher is further scoped by meters.building_id.
-- If multiple meters match same source meter number, treat as unmatched until mapped.
-- Unmatched intervals are dropped and counted in interval_count_unmatched_meter.


-- 3) Raw interval fact table
create table if not exists public.green_button_intervals (
  id bigint generated by default as identity primary key,

  org_id uuid not null references public.organizations(id) on delete cascade,
  meter_id uuid not null references public.meters(id) on delete cascade,
  import_id uuid not null references public.green_button_imports(id) on delete cascade,

  interval_start_utc timestamptz not null,
  duration_seconds integer not null check (duration_seconds > 0),

  -- Preserve raw energy value from source in Wh
  value_wh numeric(18,6) not null check (value_wh >= 0),

  -- Optional source context
  reading_type text null,
  quality_flags jsonb not null default '{}'::jsonb,
  source_payload jsonb null,

  created_at timestamptz not null default now(),

  constraint green_button_interval_unique
    unique (meter_id, interval_start_utc, duration_seconds)
);

create index if not exists green_button_intervals_org_meter_time_idx
  on public.green_button_intervals (org_id, meter_id, interval_start_utc);

create index if not exists green_button_intervals_import_idx
  on public.green_button_intervals (import_id);


-- Optional helper view for quick analytics (hour bucket)
create or replace view public.green_button_intervals_hourly as
select
  org_id,
  meter_id,
  date_trunc('hour', interval_start_utc) as hour_start_utc,
  sum(value_wh) / 1000.0 as kwh
from public.green_button_intervals
group by org_id, meter_id, date_trunc('hour', interval_start_utc);
