-- ENERGY STAR snapshot history for month-over-month and year-over-year comparisons.
-- One row per building + PM metric month + sync date.
create table if not exists public.pm_property_metric_snapshots (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  pm_property_id text not null,
  metric_as_of_date date not null,
  snapshot_date date not null default current_date,
  captured_at timestamp with time zone not null default now(),
  score numeric,
  site_eui_kbtu_ft2 numeric,
  source_eui_kbtu_ft2 numeric,
  site_eui_wn_kbtu_ft2 numeric,
  source_eui_wn_kbtu_ft2 numeric,
  notes jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  constraint pm_property_metric_snapshots_daily_unique
    unique (building_id, metric_as_of_date, snapshot_date)
);

create index if not exists pm_property_metric_snapshots_org_idx
  on public.pm_property_metric_snapshots (org_id);

create index if not exists pm_property_metric_snapshots_property_idx
  on public.pm_property_metric_snapshots (pm_property_id, metric_as_of_date desc);

create index if not exists pm_property_metric_snapshots_building_idx
  on public.pm_property_metric_snapshots (building_id, snapshot_date desc);

-- Green Button interval analytics schema.
-- Ingestion rule: match building by filename address (or explicit building_id).

create table if not exists public.green_button_imports (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid null references public.buildings(id) on delete set null,
  uploaded_by uuid null references auth.users(id) on delete set null,
  source_utility text not null default 'evergy',
  source_filename text not null,
  file_checksum_sha256 text not null,
  source_meter_identifier text null,
  source_usage_point_id text null,
  status text not null default 'uploaded'
    check (status in ('uploaded', 'parsed', 'loaded', 'failed')),
  interval_count_parsed integer not null default 0,
  interval_count_inserted integer not null default 0,
  interval_count_deduped integer not null default 0,
  interval_count_rejected integer not null default 0,
  interval_count_unmatched_meter integer not null default 0,
  error_summary jsonb not null default '{}'::jsonb,
  import_notes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists green_button_imports_checksum_uidx
  on public.green_button_imports (org_id, file_checksum_sha256);

create index if not exists green_button_imports_org_status_idx
  on public.green_button_imports (org_id, status, created_at desc);

drop table if exists public.green_button_meter_mappings cascade;

create table if not exists public.green_button_intervals (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  import_id uuid not null references public.green_button_imports(id) on delete cascade,
  interval_start_utc timestamptz not null,
  duration_seconds integer not null check (duration_seconds > 0),
  value_raw bigint null check (value_raw is null or value_raw >= 0),
  value_normalized numeric(18,6) null check (value_normalized is null or value_normalized >= 0),
  value_wh numeric(18,6) null check (value_wh is null or value_wh >= 0),
  value_kwh numeric(18,6) null check (value_kwh is null or value_kwh >= 0),
  stream_role text not null default 'other'
    check (stream_role in ('consumption', 'export', 'demand', 'other')),
  usage_point_id_urn text not null default '',
  meter_reading_id_urn text not null default '',
  reading_type_id_urn text not null default '',
  reading_type_ref text not null default '',
  reading_type_uom integer null,
  reading_type_power_of_ten_multiplier integer not null default 0,
  reading_type_interval_length integer null check (reading_type_interval_length is null or reading_type_interval_length > 0),
  reading_type_kind integer null,
  reading_type_commodity integer null,
  reading_type_flow_direction integer null,
  reading_type_accumulation_behaviour integer null,
  is_duplicate boolean not null default false,
  canonical_stream_id text not null default '',
  duplicate_reason text null,
  source_meter_identifier text null,
  source_reading_ref text not null default '',
  source_usage_point_id text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint green_button_interval_unique
    unique (building_id, source_usage_point_id, source_reading_ref, interval_start_utc, duration_seconds)
);

alter table if exists public.green_button_imports
  add column if not exists building_id uuid references public.buildings(id) on delete set null;

alter table if exists public.green_button_imports
  add column if not exists source_usage_point_id text null;

drop view if exists public.green_button_intervals_hourly;

alter table if exists public.green_button_intervals
  add column if not exists building_id uuid references public.buildings(id) on delete cascade;

alter table if exists public.green_button_intervals
  drop column if exists meter_id;

alter table if exists public.green_button_intervals
  add column if not exists source_usage_point_id text not null default '';

alter table if exists public.green_button_intervals
  add column if not exists source_meter_identifier text null;

alter table if exists public.green_button_intervals
  add column if not exists source_reading_ref text not null default '';

alter table if exists public.green_button_intervals
  add column if not exists value_raw bigint null;

alter table if exists public.green_button_intervals
  add column if not exists value_normalized numeric(18,6) null;

alter table if exists public.green_button_intervals
  add column if not exists value_kwh numeric(18,6) null;

alter table if exists public.green_button_intervals
  add column if not exists stream_role text not null default 'other';

alter table if exists public.green_button_intervals
  add column if not exists usage_point_id_urn text not null default '';

alter table if exists public.green_button_intervals
  add column if not exists meter_reading_id_urn text not null default '';

alter table if exists public.green_button_intervals
  add column if not exists reading_type_id_urn text not null default '';

alter table if exists public.green_button_intervals
  add column if not exists reading_type_ref text not null default '';

alter table if exists public.green_button_intervals
  add column if not exists reading_type_uom integer null;

alter table if exists public.green_button_intervals
  add column if not exists reading_type_power_of_ten_multiplier integer not null default 0;

alter table if exists public.green_button_intervals
  add column if not exists reading_type_interval_length integer null;

alter table if exists public.green_button_intervals
  add column if not exists reading_type_kind integer null;

alter table if exists public.green_button_intervals
  add column if not exists reading_type_commodity integer null;

alter table if exists public.green_button_intervals
  add column if not exists reading_type_flow_direction integer null;

alter table if exists public.green_button_intervals
  add column if not exists reading_type_accumulation_behaviour integer null;

alter table if exists public.green_button_intervals
  add column if not exists is_duplicate boolean not null default false;

alter table if exists public.green_button_intervals
  add column if not exists canonical_stream_id text not null default '';

alter table if exists public.green_button_intervals
  add column if not exists duplicate_reason text null;

alter table if exists public.green_button_intervals
  drop constraint if exists green_button_intervals_duplicate_reason_check;

alter table if exists public.green_button_intervals
  add constraint green_button_intervals_duplicate_reason_check
    check (
      duplicate_reason is null
      or duplicate_reason in ('identical_interval_series')
    );

alter table if exists public.green_button_intervals
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.green_button_intervals
  alter column value_wh drop not null;

alter table if exists public.green_button_intervals
  drop constraint if exists green_button_intervals_stream_role_check;

alter table if exists public.green_button_intervals
  add constraint green_button_intervals_stream_role_check
    check (stream_role in ('consumption', 'export', 'demand', 'other'));

alter table if exists public.green_button_intervals
  drop constraint if exists green_button_intervals_value_raw_check;

alter table if exists public.green_button_intervals
  add constraint green_button_intervals_value_raw_check
    check (value_raw is null or value_raw >= 0);

alter table if exists public.green_button_intervals
  drop constraint if exists green_button_intervals_value_normalized_check;

alter table if exists public.green_button_intervals
  add constraint green_button_intervals_value_normalized_check
    check (value_normalized is null or value_normalized >= 0);

alter table if exists public.green_button_intervals
  drop constraint if exists green_button_intervals_value_wh_check;

alter table if exists public.green_button_intervals
  add constraint green_button_intervals_value_wh_check
    check (value_wh is null or value_wh >= 0);

alter table if exists public.green_button_intervals
  drop constraint if exists green_button_intervals_value_kwh_check;

alter table if exists public.green_button_intervals
  add constraint green_button_intervals_value_kwh_check
    check (value_kwh is null or value_kwh >= 0);

alter table if exists public.green_button_intervals
  drop column if exists reading_type;

alter table if exists public.green_button_intervals
  drop column if exists quality_flags;

alter table if exists public.green_button_intervals
  drop column if exists source_payload;

alter table if exists public.green_button_intervals
  drop constraint if exists green_button_interval_unique;

alter table if exists public.green_button_intervals
  add constraint green_button_interval_unique
  unique (building_id, source_usage_point_id, source_reading_ref, interval_start_utc, duration_seconds);

create index if not exists green_button_intervals_org_building_time_idx
  on public.green_button_intervals (org_id, building_id, interval_start_utc);

create index if not exists green_button_intervals_import_idx
  on public.green_button_intervals (import_id);

create index if not exists green_button_intervals_duplicate_filter_idx
  on public.green_button_intervals (org_id, building_id, is_duplicate, interval_start_utc);

create index if not exists green_button_intervals_canonical_stream_idx
  on public.green_button_intervals (org_id, building_id, canonical_stream_id, interval_start_utc);

drop view if exists public.green_button_kpi_guardrail_v;
drop view if exists public.green_button_intervals_analytics_v cascade;

create view public.green_button_intervals_analytics_v as
select *
from public.green_button_intervals
where coalesce(is_duplicate, false) = false
  and coalesce(stream_role, 'other') in ('consumption', 'other')
  and value_wh is not null;

create view public.green_button_kpi_guardrail_v as
with stream_points as (
  select
    org_id,
    building_id,
    interval_start_utc,
    canonical_stream_id,
    sum(value_wh)::numeric(18,6) as stream_value_wh,
    sum(value_wh) / 1000.0 as stream_kwh,
    sum((value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0)::numeric(18,6) as stream_kw
  from public.green_button_intervals_analytics_v
  group by org_id, building_id, interval_start_utc, canonical_stream_id
),
building_points as (
  select
    org_id,
    building_id,
    interval_start_utc,
    sum(stream_value_wh)::numeric(18,6) as building_value_wh,
    sum(stream_kwh)::numeric(18,6) as building_kwh,
    sum(stream_kw)::numeric(18,6) as building_kw,
    count(*)::integer as canonical_stream_count
  from stream_points
  group by org_id, building_id, interval_start_utc
)
select
  s.org_id,
  s.building_id,
  s.interval_start_utc,
  s.canonical_stream_id,
  s.stream_value_wh,
  s.stream_kwh,
  s.stream_kw,
  b.building_value_wh,
  b.building_kwh,
  b.building_kw,
  b.canonical_stream_count
from stream_points s
join building_points b
  on b.org_id = s.org_id
 and b.building_id = s.building_id
 and b.interval_start_utc = s.interval_start_utc;

create view public.green_button_intervals_hourly as
select
  org_id,
  building_id,
  date_trunc('hour', interval_start_utc) as hour_start_utc,
  sum(value_wh) / 1000.0 as kwh
from public.green_button_intervals_analytics_v
group by org_id, building_id, date_trunc('hour', interval_start_utc);

drop materialized view if exists public.green_button_monthly_energy_mv;

create table if not exists public.green_button_monthly_energy_history (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  month_start date not null,
  kwh_total numeric(18,6) not null check (kwh_total >= 0),
  source text not null default 'archived',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint green_button_monthly_energy_history_unique
    unique (org_id, building_id, month_start)
);

create index if not exists green_button_monthly_energy_history_org_month_idx
  on public.green_button_monthly_energy_history (org_id, month_start desc);

create materialized view public.green_button_monthly_energy_mv as
with raw_monthly as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_utc)::date as month_start,
    sum(value_wh) / 1000.0 as kwh_total
  from public.green_button_intervals_analytics_v
  group by
    org_id,
    building_id,
    date_trunc('month', interval_start_utc)
),
combined as (
  select
    org_id,
    building_id,
    month_start,
    kwh_total,
    2 as source_rank
  from raw_monthly
  union all
  select
    org_id,
    building_id,
    month_start,
    kwh_total,
    1 as source_rank
  from public.green_button_monthly_energy_history
),
final_ranked as (
  select
    org_id,
    building_id,
    month_start,
    kwh_total,
    row_number() over (
      partition by org_id, building_id, month_start
      order by source_rank desc
    ) as rn
  from combined
)
select
  org_id,
  building_id,
  month_start,
  kwh_total,
  now() as refreshed_at
from final_ranked
where rn = 1;

create unique index if not exists green_button_monthly_energy_mv_uidx
  on public.green_button_monthly_energy_mv (org_id, building_id, month_start);

create index if not exists green_button_monthly_energy_mv_org_month_idx
  on public.green_button_monthly_energy_mv (org_id, month_start desc);

create or replace function public.refresh_green_button_monthly_energy_mv()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows bigint := 0;
begin
  refresh materialized view public.green_button_monthly_energy_mv;

  select count(*) into v_rows
  from public.green_button_monthly_energy_mv;

  return jsonb_build_object(
    'ok', true,
    'rows', v_rows,
    'refreshed_at', now()
  );
end;
$$;

-- Append-only Green Button KPI snapshots (building-level only).
-- These tables are for long-term historical retention with local-time monthly boundaries.

create table if not exists public.green_button_historical_district_energy_use (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null,
  snapshot_at timestamptz not null default now(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  building_timezone text not null,
  month_start date not null,
  month_end date not null,
  source_data_start_utc timestamptz not null,
  source_data_end_utc timestamptz not null,
  expected_seconds integer not null check (expected_seconds > 0),
  observed_seconds integer not null check (observed_seconds > 0),
  district_energy_use_kwh numeric(18,6) not null check (district_energy_use_kwh >= 0),
  created_at timestamptz not null default now(),
  constraint gb_hist_energy_snapshot_unique
    unique (snapshot_id, org_id, building_id, month_start)
);

create index if not exists gb_hist_energy_org_month_idx
  on public.green_button_historical_district_energy_use (org_id, month_start desc, snapshot_at desc);

create table if not exists public.green_button_historical_district_peak_demand (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null,
  snapshot_at timestamptz not null default now(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  building_timezone text not null,
  month_start date not null,
  month_end date not null,
  source_data_start_utc timestamptz not null,
  source_data_end_utc timestamptz not null,
  expected_seconds integer not null check (expected_seconds > 0),
  observed_seconds integer not null check (observed_seconds > 0),
  district_peak_demand_kw numeric(18,6) not null check (district_peak_demand_kw >= 0),
  peak_interval_start_utc timestamptz null,
  created_at timestamptz not null default now(),
  constraint gb_hist_peak_snapshot_unique
    unique (snapshot_id, org_id, building_id, month_start)
);

create index if not exists gb_hist_peak_org_month_idx
  on public.green_button_historical_district_peak_demand (org_id, month_start desc, snapshot_at desc);

create table if not exists public.green_button_historical_night_baseload (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null,
  snapshot_at timestamptz not null default now(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  building_timezone text not null,
  month_start date not null,
  month_end date not null,
  source_data_start_utc timestamptz not null,
  source_data_end_utc timestamptz not null,
  expected_seconds integer not null check (expected_seconds > 0),
  observed_seconds integer not null check (observed_seconds > 0),
  weekday_2am_avg_kw numeric(18,6) null check (weekday_2am_avg_kw is null or weekday_2am_avg_kw >= 0),
  peak_weekday_kw numeric(18,6) null check (peak_weekday_kw is null or peak_weekday_kw >= 0),
  night_baseload_pct numeric(9,4) null check (night_baseload_pct is null or night_baseload_pct >= 0),
  created_at timestamptz not null default now(),
  constraint gb_hist_night_base_snapshot_unique
    unique (snapshot_id, org_id, building_id, month_start)
);

create index if not exists gb_hist_night_base_org_month_idx
  on public.green_button_historical_night_baseload (org_id, month_start desc, snapshot_at desc);

create table if not exists public.green_button_historical_weekend_operations_index (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null,
  snapshot_at timestamptz not null default now(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  building_timezone text not null,
  month_start date not null,
  month_end date not null,
  source_data_start_utc timestamptz not null,
  source_data_end_utc timestamptz not null,
  expected_seconds integer not null check (expected_seconds > 0),
  observed_seconds integer not null check (observed_seconds > 0),
  weekend_kwh_avg numeric(18,6) null check (weekend_kwh_avg is null or weekend_kwh_avg >= 0),
  weekday_kwh_avg numeric(18,6) null check (weekday_kwh_avg is null or weekday_kwh_avg >= 0),
  weekend_operations_index_pct numeric(9,4) null check (weekend_operations_index_pct is null or weekend_operations_index_pct >= 0),
  weekend_days_count integer not null default 0 check (weekend_days_count >= 0),
  weekday_days_count integer not null default 0 check (weekday_days_count >= 0),
  created_at timestamptz not null default now(),
  constraint gb_hist_weekend_ops_snapshot_unique
    unique (snapshot_id, org_id, building_id, month_start)
);

create index if not exists gb_hist_weekend_ops_org_month_idx
  on public.green_button_historical_weekend_operations_index (org_id, month_start desc, snapshot_at desc);

create table if not exists public.green_button_historical_load_shape_weekday (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null,
  snapshot_at timestamptz not null default now(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  building_timezone text not null,
  month_start date not null,
  month_end date not null,
  source_data_start_utc timestamptz not null,
  source_data_end_utc timestamptz not null,
  expected_seconds integer not null check (expected_seconds > 0),
  observed_seconds integer not null check (observed_seconds > 0),
  slot_index smallint not null check (slot_index >= 0 and slot_index <= 95),
  hhmm text not null,
  avg_kw numeric(18,6) not null check (avg_kw >= 0),
  intervals_count integer not null default 0 check (intervals_count >= 0),
  weekday_days_count integer not null default 0 check (weekday_days_count >= 0),
  created_at timestamptz not null default now(),
  constraint gb_hist_load_shape_snapshot_unique
    unique (snapshot_id, org_id, building_id, month_start, slot_index)
);

create index if not exists gb_hist_load_shape_org_month_idx
  on public.green_button_historical_load_shape_weekday (org_id, month_start desc, snapshot_at desc);

create or replace function public.snapshot_green_button_historical_monthly_kpis(
  p_org_id uuid,
  p_snapshot_at timestamptz default now(),
  p_month_starts date[] default null,
  p_building_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_snapshot_id uuid := gen_random_uuid();
  v_complete_months bigint := 0;
  v_energy_rows bigint := 0;
  v_peak_rows bigint := 0;
  v_night_rows bigint := 0;
  v_weekend_rows bigint := 0;
  v_shape_rows bigint := 0;
begin
  if p_org_id is null then
    raise exception 'p_org_id is required';
  end if;

  with building_tz as (
    select
      b.id as building_id,
      b.org_id,
      coalesce(
        nullif(to_jsonb(b) ->> 'timezone', ''),
        nullif(to_jsonb(b) ->> 'time_zone', ''),
        nullif(to_jsonb(b) ->> 'tz', ''),
        'America/Chicago'
      ) as building_timezone
    from public.buildings b
    where b.org_id = p_org_id
      and (p_building_id is null or b.id = p_building_id)
  ),
  interval_agg as (
    select
      i.org_id,
      i.building_id,
      i.interval_start_utc,
      max(i.duration_seconds)::integer as duration_seconds,
      sum(i.value_wh)::numeric(18,6) as value_wh
    from public.green_button_intervals_analytics_v i
    where i.org_id = p_org_id
      and (p_building_id is null or i.building_id = p_building_id)
      and i.duration_seconds > 0
    group by i.org_id, i.building_id, i.interval_start_utc
  ),
  base_points as (
    select
      ia.org_id,
      ia.building_id,
      bt.building_timezone,
      ia.interval_start_utc,
      ia.duration_seconds,
      ia.value_wh,
      ia.interval_start_utc at time zone bt.building_timezone as interval_start_local,
      date_trunc('month', ia.interval_start_utc at time zone bt.building_timezone)::date as month_start
    from interval_agg ia
    join building_tz bt
      on bt.org_id = ia.org_id
     and bt.building_id = ia.building_id
    where ia.org_id = p_org_id
      and (p_building_id is null or ia.building_id = p_building_id)
      and ia.duration_seconds > 0
      and (
        coalesce(array_length(p_month_starts, 1), 0) = 0
        or date_trunc('month', ia.interval_start_utc at time zone bt.building_timezone)::date = any(p_month_starts)
      )
  ),
  month_bounds as (
    select distinct
      org_id,
      building_id,
      building_timezone,
      month_start,
      (month_start::timestamp at time zone building_timezone) as month_start_utc,
      ((month_start + interval '1 month')::timestamp at time zone building_timezone) as month_end_utc
    from base_points
  ),
  month_coverage as (
    select
      mb.org_id,
      mb.building_id,
      mb.building_timezone,
      mb.month_start,
      (mb.month_start + interval '1 month')::date as month_end,
      mb.month_start_utc,
      mb.month_end_utc,
      extract(epoch from (mb.month_end_utc - mb.month_start_utc))::integer as expected_seconds,
      coalesce(sum(bp.duration_seconds), 0)::integer as observed_seconds,
      count(distinct date(bp.interval_start_local))::integer as covered_days_count,
      extract(day from ((mb.month_start + interval '1 month')::date - interval '1 day'))::integer as expected_days_count
    from month_bounds mb
    left join base_points bp
      on bp.org_id = mb.org_id
     and bp.building_id = mb.building_id
     and bp.interval_start_utc >= mb.month_start_utc
     and bp.interval_start_utc < mb.month_end_utc
    group by
      mb.org_id,
      mb.building_id,
      mb.building_timezone,
      mb.month_start,
      mb.month_start_utc,
      mb.month_end_utc
  ),
  complete_months as (
    select
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds
    from month_coverage
    where observed_seconds >= expected_seconds
      and covered_days_count >= expected_days_count
  ),
  scoped_points as (
    select
      bp.org_id,
      bp.building_id,
      cm.building_timezone,
      cm.month_start,
      cm.month_end,
      cm.month_start_utc,
      cm.month_end_utc,
      cm.expected_seconds,
      cm.observed_seconds,
      bp.interval_start_utc,
      bp.interval_start_local,
      bp.duration_seconds,
      bp.value_wh,
      (bp.value_wh * 3600.0) / nullif(bp.duration_seconds, 0) / 1000.0 as kw,
      (bp.value_wh / 1000.0) as kwh
    from base_points bp
    join complete_months cm
      on cm.org_id = bp.org_id
     and cm.building_id = bp.building_id
     and bp.interval_start_utc >= cm.month_start_utc
     and bp.interval_start_utc < cm.month_end_utc
  ),
  inserted_energy as (
    insert into public.green_button_historical_district_energy_use (
      snapshot_id,
      snapshot_at,
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      source_data_start_utc,
      source_data_end_utc,
      expected_seconds,
      observed_seconds,
      district_energy_use_kwh
    )
    select
      v_snapshot_id,
      p_snapshot_at,
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds,
      sum(value_wh) / 1000.0 as district_energy_use_kwh
    from scoped_points
    group by
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds
    returning 1
  ),
  peak_ranked as (
    select
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds,
      kw,
      interval_start_utc,
      row_number() over (
        partition by org_id, building_id, month_start
        order by kw desc, interval_start_utc desc
      ) as rn
    from scoped_points
  ),
  inserted_peak as (
    insert into public.green_button_historical_district_peak_demand (
      snapshot_id,
      snapshot_at,
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      source_data_start_utc,
      source_data_end_utc,
      expected_seconds,
      observed_seconds,
      district_peak_demand_kw,
      peak_interval_start_utc
    )
    select
      v_snapshot_id,
      p_snapshot_at,
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds,
      kw as district_peak_demand_kw,
      interval_start_utc as peak_interval_start_utc
    from peak_ranked
    where rn = 1
    returning 1
  ),
  weekday_points as (
    select
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds,
      interval_start_local,
      kw,
      kwh
    from scoped_points
    where extract(isodow from interval_start_local) between 1 and 5
  ),
  inserted_night as (
    insert into public.green_button_historical_night_baseload (
      snapshot_id,
      snapshot_at,
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      source_data_start_utc,
      source_data_end_utc,
      expected_seconds,
      observed_seconds,
      weekday_2am_avg_kw,
      peak_weekday_kw,
      night_baseload_pct
    )
    select
      v_snapshot_id,
      p_snapshot_at,
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds,
      avg(kw) filter (where extract(hour from interval_start_local) = 2)::numeric(18,6) as weekday_2am_avg_kw,
      max(kw)::numeric(18,6) as peak_weekday_kw,
      case
        when max(kw) > 0
          then (100.0 * avg(kw) filter (where extract(hour from interval_start_local) = 2) / max(kw))::numeric(9,4)
        else null
      end as night_baseload_pct
    from weekday_points
    group by
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds
    returning 1
  ),
  weekend_daily as (
    select
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds,
      date(interval_start_local) as local_day,
      sum(kwh)::numeric(18,6) as day_kwh
    from scoped_points
    group by
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds,
      date(interval_start_local)
  ),
  inserted_weekend as (
    insert into public.green_button_historical_weekend_operations_index (
      snapshot_id,
      snapshot_at,
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      source_data_start_utc,
      source_data_end_utc,
      expected_seconds,
      observed_seconds,
      weekend_kwh_avg,
      weekday_kwh_avg,
      weekend_operations_index_pct,
      weekend_days_count,
      weekday_days_count
    )
    select
      v_snapshot_id,
      p_snapshot_at,
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds,
      avg(day_kwh) filter (where extract(isodow from local_day) in (6, 7))::numeric(18,6) as weekend_kwh_avg,
      avg(day_kwh) filter (where extract(isodow from local_day) between 1 and 5)::numeric(18,6) as weekday_kwh_avg,
      case
        when avg(day_kwh) filter (where extract(isodow from local_day) between 1 and 5) > 0
          then (
            100.0
            * avg(day_kwh) filter (where extract(isodow from local_day) in (6, 7))
            / avg(day_kwh) filter (where extract(isodow from local_day) between 1 and 5)
          )::numeric(9,4)
        else null
      end as weekend_operations_index_pct,
      count(*) filter (where extract(isodow from local_day) in (6, 7))::integer as weekend_days_count,
      count(*) filter (where extract(isodow from local_day) between 1 and 5)::integer as weekday_days_count
    from weekend_daily
    group by
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds
    returning 1
  ),
  weekday_shape_points as (
    select
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds,
      date(interval_start_local) as local_day,
      extract(hour from interval_start_local)::integer as local_hour,
      floor(extract(minute from interval_start_local) / 15.0)::integer as quarter_hour,
      kw
    from scoped_points
    where extract(isodow from interval_start_local) between 1 and 5
  ),
  inserted_shape as (
    insert into public.green_button_historical_load_shape_weekday (
      snapshot_id,
      snapshot_at,
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      source_data_start_utc,
      source_data_end_utc,
      expected_seconds,
      observed_seconds,
      slot_index,
      hhmm,
      avg_kw,
      intervals_count,
      weekday_days_count
    )
    select
      v_snapshot_id,
      p_snapshot_at,
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds,
      (local_hour * 4 + quarter_hour)::smallint as slot_index,
      lpad(local_hour::text, 2, '0') || ':' || lpad((quarter_hour * 15)::text, 2, '0') as hhmm,
      avg(kw)::numeric(18,6) as avg_kw,
      count(*)::integer as intervals_count,
      count(distinct local_day)::integer as weekday_days_count
    from weekday_shape_points
    where quarter_hour between 0 and 3
    group by
      org_id,
      building_id,
      building_timezone,
      month_start,
      month_end,
      month_start_utc,
      month_end_utc,
      expected_seconds,
      observed_seconds,
      local_hour,
      quarter_hour
    returning 1
  )
  select
    (select count(*)::bigint from complete_months),
    (select count(*)::bigint from inserted_energy),
    (select count(*)::bigint from inserted_peak),
    (select count(*)::bigint from inserted_night),
    (select count(*)::bigint from inserted_weekend),
    (select count(*)::bigint from inserted_shape)
  into
    v_complete_months,
    v_energy_rows,
    v_peak_rows,
    v_night_rows,
    v_weekend_rows,
    v_shape_rows;

  return jsonb_build_object(
    'snapshot_id', v_snapshot_id,
    'snapshot_at', p_snapshot_at,
    'complete_months_snapshotted', v_complete_months,
    'energy_rows_inserted', v_energy_rows,
    'peak_rows_inserted', v_peak_rows,
    'night_baseload_rows_inserted', v_night_rows,
    'weekend_ops_rows_inserted', v_weekend_rows,
    'load_shape_rows_inserted', v_shape_rows,
    'timezone_basis', 'stored interval clock basis (interval_start_utc at time zone UTC)'
  );
end;
$$;

grant select on public.green_button_historical_district_energy_use to authenticated;
grant select on public.green_button_historical_district_peak_demand to authenticated;
grant select on public.green_button_historical_night_baseload to authenticated;
grant select on public.green_button_historical_weekend_operations_index to authenticated;
grant select on public.green_button_historical_load_shape_weekday to authenticated;
grant execute on function public.snapshot_green_button_historical_monthly_kpis(uuid, timestamptz, date[], uuid) to authenticated;
grant execute on function public.snapshot_green_button_historical_monthly_kpis(uuid, timestamptz, date[], uuid) to service_role;

drop view if exists public.green_button_org_stats_v;

create or replace view public.green_button_monthly_peak_kw_v as
with raw_ranked as (
  select
    i.org_id,
    i.building_id,
    date_trunc(
      'month',
      i.interval_start_utc at time zone 'UTC'
    )::date as month_start,
    i.interval_start_utc,
    (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 as kw,
    row_number() over (
      partition by
        i.org_id,
        i.building_id,
        date_trunc(
          'month',
          i.interval_start_utc at time zone 'UTC'
        )
      order by
        (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 desc,
        i.interval_start_utc desc
    ) as rn
  from public.green_button_intervals_analytics_v i
  left join public.buildings b
    on b.id = i.building_id
  where i.duration_seconds > 0
)
select
  org_id,
  building_id,
  month_start,
  kw as peak_kw,
  interval_start_utc as peak_interval_start_utc
from raw_ranked
where rn = 1;

create table if not exists public.green_button_monthly_peak_history (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  month_start date not null,
  peak_kw numeric(18,6) not null check (peak_kw >= 0),
  peak_interval_start_utc timestamptz null,
  source text not null default 'archived',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint green_button_monthly_peak_history_unique
    unique (org_id, building_id, month_start)
);

create index if not exists green_button_monthly_peak_history_org_month_idx
  on public.green_button_monthly_peak_history (org_id, month_start desc);

create table if not exists public.green_button_monthly_peak_cache (
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  month_start date not null,
  peak_kw numeric(18,6) not null check (peak_kw >= 0),
  peak_interval_start_utc timestamptz null,
  refreshed_at timestamptz not null default now(),
  primary key (org_id, building_id, month_start)
);

create index if not exists green_button_monthly_peak_cache_org_month_idx
  on public.green_button_monthly_peak_cache (org_id, month_start desc);

create or replace function public.refresh_green_button_monthly_peak_cache(
  p_org_id uuid,
  p_building_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows bigint := 0;
begin
  if p_org_id is null then
    raise exception 'p_org_id is required';
  end if;

  delete from public.green_button_monthly_peak_cache
  where org_id = p_org_id
    and (p_building_id is null or building_id = p_building_id);

  with raw_ranked as (
    select
      i.org_id,
      i.building_id,
      date_trunc(
        'month',
        i.interval_start_utc at time zone 'UTC'
      )::date as month_start,
      i.interval_start_utc,
      (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 as peak_kw,
      row_number() over (
        partition by
          i.org_id,
          i.building_id,
          date_trunc(
            'month',
            i.interval_start_utc at time zone 'UTC'
          )
        order by
          (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 desc,
          i.interval_start_utc desc
      ) as rn
    from public.green_button_intervals_analytics_v i
    where i.org_id = p_org_id
      and (p_building_id is null or i.building_id = p_building_id)
      and i.duration_seconds > 0
  ),
  raw_monthly as (
    select
      org_id,
      building_id,
      month_start,
      peak_kw,
      interval_start_utc as peak_interval_start_utc
    from raw_ranked
    where rn = 1
  ),
  combined as (
    select org_id, building_id, month_start, peak_kw, peak_interval_start_utc
    from raw_monthly
    union all
    select org_id, building_id, month_start, peak_kw, peak_interval_start_utc
    from public.green_button_monthly_peak_history
    where org_id = p_org_id
      and (p_building_id is null or building_id = p_building_id)
  ),
  final_ranked as (
    select
      org_id,
      building_id,
      month_start,
      peak_kw,
      peak_interval_start_utc,
      row_number() over (
        partition by org_id, building_id, month_start
        order by peak_kw desc, peak_interval_start_utc desc nulls last
      ) as rn
    from combined
  ),
  final_rows as (
    select org_id, building_id, month_start, peak_kw, peak_interval_start_utc
    from final_ranked
    where rn = 1
  ),
  inserted as (
    insert into public.green_button_monthly_peak_cache (
      org_id,
      building_id,
      month_start,
      peak_kw,
      peak_interval_start_utc,
      refreshed_at
    )
    select
      org_id,
      building_id,
      month_start,
      peak_kw,
      peak_interval_start_utc,
      now()
    from final_rows
    returning 1
  )
  select count(*)::bigint into v_rows from inserted;

  return jsonb_build_object(
    'org_id', p_org_id,
    'building_id', p_building_id,
    'rows_refreshed', v_rows
  );
end;
$$;

create table if not exists public.green_button_monthly_top_peaks_history (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  month_start date not null,
  peak_rank integer not null check (peak_rank between 1 and 5),
  peak_kw numeric(18,6) not null check (peak_kw >= 0),
  peak_interval_start_utc timestamptz null,
  source text not null default 'archived',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint green_button_monthly_top_peaks_history_unique
    unique (org_id, building_id, month_start, peak_rank)
);

create index if not exists green_button_monthly_top_peaks_history_org_month_idx
  on public.green_button_monthly_top_peaks_history (org_id, month_start desc);

drop materialized view if exists public.green_button_monthly_top_peaks_mv;

create materialized view public.green_button_monthly_top_peaks_mv as
with raw_ranked as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_utc)::date as month_start,
    (value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0 as peak_kw,
    interval_start_utc as peak_interval_start_utc,
    row_number() over (
      partition by org_id, building_id, date_trunc('month', interval_start_utc)
      order by
        (value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0 desc,
        interval_start_utc desc
    ) as peak_rank
  from public.green_button_intervals_analytics_v
  where duration_seconds > 0
),
raw_top as (
  select
    org_id,
    building_id,
    month_start,
    peak_rank,
    peak_kw,
    peak_interval_start_utc,
    2 as source_rank
  from raw_ranked
  where peak_rank <= 5
),
history_top as (
  select
    org_id,
    building_id,
    month_start,
    peak_rank,
    peak_kw,
    peak_interval_start_utc,
    1 as source_rank
  from public.green_button_monthly_top_peaks_history
),
combined as (
  select * from raw_top
  union all
  select * from history_top
),
final_ranked as (
  select
    org_id,
    building_id,
    month_start,
    peak_rank,
    peak_kw,
    peak_interval_start_utc,
    row_number() over (
      partition by org_id, building_id, month_start, peak_rank
      order by source_rank desc
    ) as rn
  from combined
)
select
  org_id,
  building_id,
  month_start,
  peak_rank,
  peak_kw,
  peak_interval_start_utc
from final_ranked
where rn = 1;

create unique index if not exists green_button_monthly_top_peaks_mv_uidx
  on public.green_button_monthly_top_peaks_mv (org_id, building_id, month_start, peak_rank);

create index if not exists green_button_monthly_top_peaks_mv_org_month_idx
  on public.green_button_monthly_top_peaks_mv (org_id, month_start desc);

create or replace function public.refresh_green_button_monthly_top_peaks_mv()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows bigint := 0;
begin
  perform set_config('statement_timeout', '0', true);
  refresh materialized view public.green_button_monthly_top_peaks_mv;

  select count(*)::bigint
    into v_rows
  from public.green_button_monthly_top_peaks_mv;

  return jsonb_build_object(
    'rows_refreshed', v_rows
  );
end;
$$;

create table if not exists public.green_button_startup_intensity_monthly_history (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  month_start date not null,
  max_ramp_kw numeric(18,6) not null check (max_ramp_kw >= 0),
  ramp_interval_start_utc timestamptz null,
  source text not null default 'archived',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint green_button_startup_intensity_monthly_history_unique
    unique (org_id, building_id, month_start)
);

create index if not exists green_button_startup_intensity_monthly_history_org_month_idx
  on public.green_button_startup_intensity_monthly_history (org_id, month_start desc);

drop materialized view if exists public.green_button_startup_intensity_monthly_mv;

create materialized view public.green_button_startup_intensity_monthly_mv as
with interval_points as (
  select
    i.org_id,
    i.building_id,
    i.interval_start_utc,
    i.interval_start_utc at time zone 'UTC' as interval_start_local,
    (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 as kw
  from public.green_button_intervals_analytics_v i
  where i.duration_seconds > 0
),
ramp_points as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_local)::date as month_start,
    interval_start_utc as ramp_interval_start_utc,
    interval_start_local,
    kw - lag(kw) over (
      partition by org_id, building_id
      order by interval_start_utc
    ) as ramp_kw
  from interval_points
),
ranked as (
  select
    org_id,
    building_id,
    month_start,
    ramp_kw as max_ramp_kw,
    ramp_interval_start_utc,
    row_number() over (
      partition by org_id, building_id, month_start
      order by ramp_kw desc, ramp_interval_start_utc desc
    ) as rn
  from ramp_points
  where extract(hour from interval_start_local) >= 4
    and extract(hour from interval_start_local) < 9
    and ramp_kw is not null
    and ramp_kw > 0
),
raw_monthly as (
  select
    org_id,
    building_id,
    month_start,
    max_ramp_kw,
    ramp_interval_start_utc
  from ranked
  where rn = 1
),
combined as (
  select org_id, building_id, month_start, max_ramp_kw, ramp_interval_start_utc
  from raw_monthly
  union all
  select org_id, building_id, month_start, max_ramp_kw, ramp_interval_start_utc
  from public.green_button_startup_intensity_monthly_history
),
final_ranked as (
  select
    org_id,
    building_id,
    month_start,
    max_ramp_kw,
    ramp_interval_start_utc,
    row_number() over (
      partition by org_id, building_id, month_start
      order by max_ramp_kw desc, ramp_interval_start_utc desc nulls last
    ) as rn
  from combined
)
select
  org_id,
  building_id,
  month_start,
  max_ramp_kw,
  ramp_interval_start_utc
from final_ranked
where rn = 1;

create unique index if not exists green_button_startup_intensity_monthly_mv_uidx
  on public.green_button_startup_intensity_monthly_mv (org_id, building_id, month_start);

create index if not exists green_button_startup_intensity_monthly_mv_org_month_idx
  on public.green_button_startup_intensity_monthly_mv (org_id, month_start desc);

create or replace function public.refresh_green_button_startup_intensity_monthly_mv()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows bigint := 0;
begin
  perform set_config('statement_timeout', '0', true);
  refresh materialized view public.green_button_startup_intensity_monthly_mv;

  select count(*)::bigint
    into v_rows
  from public.green_button_startup_intensity_monthly_mv;

  return jsonb_build_object(
    'rows_refreshed', v_rows,
    'timezone', 'stored interval clock basis (interval_start_utc at time zone UTC)'
  );
end;
$$;

create table if not exists public.green_button_peak_timing_monthly_history (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  month_start date not null,
  peak_hour_local integer not null check (peak_hour_local >= 0 and peak_hour_local <= 23),
  daily_peak_count integer not null check (daily_peak_count >= 0),
  source text not null default 'archived',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint green_button_peak_timing_monthly_history_unique
    unique (org_id, building_id, month_start, peak_hour_local)
);

create index if not exists green_button_peak_timing_monthly_history_org_month_idx
  on public.green_button_peak_timing_monthly_history (org_id, month_start desc);

drop materialized view if exists public.green_button_peak_timing_monthly_mv;

create materialized view public.green_button_peak_timing_monthly_mv as
with interval_points as (
  select
    i.org_id,
    i.building_id,
    i.interval_start_utc,
    i.interval_start_utc at time zone 'UTC' as interval_start_local,
    (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 as kw
  from public.green_button_intervals_analytics_v i
  where i.duration_seconds > 0
),
daily_ranked as (
  select
    org_id,
    building_id,
    date(interval_start_local) as local_day,
    date_trunc('month', interval_start_local)::date as month_start,
    extract(hour from interval_start_local)::integer as peak_hour_local,
    row_number() over (
      partition by org_id, building_id, date(interval_start_local)
      order by kw desc, interval_start_utc desc
    ) as rn
  from interval_points
),
raw_histogram as (
  select
    org_id,
    building_id,
    month_start,
    peak_hour_local,
    count(*)::integer as daily_peak_count
  from daily_ranked
  where rn = 1
  group by org_id, building_id, month_start, peak_hour_local
),
combined as (
  select org_id, building_id, month_start, peak_hour_local, daily_peak_count
  from raw_histogram
  union all
  select org_id, building_id, month_start, peak_hour_local, daily_peak_count
  from public.green_button_peak_timing_monthly_history
),
final_rows as (
  select
    org_id,
    building_id,
    month_start,
    peak_hour_local,
    sum(daily_peak_count)::integer as daily_peak_count
  from combined
  group by org_id, building_id, month_start, peak_hour_local
)
select
  org_id,
  building_id,
  month_start,
  peak_hour_local,
  daily_peak_count
from final_rows;

create unique index if not exists green_button_peak_timing_monthly_mv_uidx
  on public.green_button_peak_timing_monthly_mv (org_id, building_id, month_start, peak_hour_local);

create index if not exists green_button_peak_timing_monthly_mv_org_month_idx
  on public.green_button_peak_timing_monthly_mv (org_id, month_start desc);

create or replace function public.refresh_green_button_peak_timing_monthly_mv()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows bigint := 0;
begin
  perform set_config('statement_timeout', '0', true);
  refresh materialized view public.green_button_peak_timing_monthly_mv;

  select count(*)::bigint
    into v_rows
  from public.green_button_peak_timing_monthly_mv;

  return jsonb_build_object(
    'rows_refreshed', v_rows,
    'timezone', 'stored interval clock basis (interval_start_utc at time zone UTC)'
  );
end;
$$;

create table if not exists public.green_button_after_hours_load_monthly_history (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  month_start date not null,
  avg_night_min_kw numeric(18,6) not null check (avg_night_min_kw >= 0),
  nights_count integer not null check (nights_count >= 0),
  source text not null default 'archived',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint green_button_after_hours_load_monthly_history_unique
    unique (org_id, building_id, month_start)
);

create index if not exists green_button_after_hours_load_monthly_history_org_month_idx
  on public.green_button_after_hours_load_monthly_history (org_id, month_start desc);

drop materialized view if exists public.green_button_after_hours_load_monthly_mv;

create materialized view public.green_button_after_hours_load_monthly_mv as
with interval_points as (
  select
    i.org_id,
    i.building_id,
    i.interval_start_utc,
    i.interval_start_utc at time zone 'UTC' as interval_start_local,
    (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 as kw
  from public.green_button_intervals_analytics_v i
  where i.duration_seconds > 0
),
night_points as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_local)::date as month_start,
    date(interval_start_local) as local_day,
    kw,
    interval_start_utc
  from interval_points
  where extract(hour from interval_start_local) >= 22
     or extract(hour from interval_start_local) < 4
),
daily_mins as (
  select
    org_id,
    building_id,
    month_start,
    local_day,
    kw as night_min_kw,
    row_number() over (
      partition by org_id, building_id, local_day
      order by kw asc, interval_start_utc desc
    ) as rn
  from night_points
  where kw > 0
),
raw_monthly as (
  select
    org_id,
    building_id,
    month_start,
    avg(night_min_kw)::numeric(18,6) as avg_night_min_kw,
    count(*)::integer as nights_count
  from daily_mins
  where rn = 1
  group by org_id, building_id, month_start
),
combined as (
  select
    org_id,
    building_id,
    month_start,
    avg_night_min_kw,
    nights_count,
    2 as source_rank
  from raw_monthly
  union all
  select
    org_id,
    building_id,
    month_start,
    avg_night_min_kw,
    nights_count,
    1 as source_rank
  from public.green_button_after_hours_load_monthly_history
),
final_ranked as (
  select
    org_id,
    building_id,
    month_start,
    avg_night_min_kw,
    nights_count,
    row_number() over (
      partition by org_id, building_id, month_start
      order by source_rank desc
    ) as rn
  from combined
)
select
  org_id,
  building_id,
  month_start,
  avg_night_min_kw,
  nights_count
from final_ranked
where rn = 1;

create unique index if not exists green_button_after_hours_load_monthly_mv_uidx
  on public.green_button_after_hours_load_monthly_mv (org_id, building_id, month_start);

create index if not exists green_button_after_hours_load_monthly_mv_org_month_idx
  on public.green_button_after_hours_load_monthly_mv (org_id, month_start desc);

create or replace function public.refresh_green_button_after_hours_load_monthly_mv()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows bigint := 0;
begin
  perform set_config('statement_timeout', '0', true);
  refresh materialized view public.green_button_after_hours_load_monthly_mv;

  select count(*)::bigint
    into v_rows
  from public.green_button_after_hours_load_monthly_mv;

  return jsonb_build_object(
    'rows_refreshed', v_rows,
    'timezone', 'stored interval clock basis (interval_start_utc at time zone UTC)'
  );
end;
$$;

drop materialized view if exists public.green_button_after_hours_pct_monthly_mv;
drop view if exists public.green_button_after_hours_pct_monthly_mv;

create materialized view public.green_button_after_hours_pct_monthly_mv as
with interval_points as (
  select
    i.org_id,
    i.building_id,
    i.interval_start_utc at time zone 'UTC' as interval_start_local,
    i.source_usage_point_id,
    (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 as kw
  from public.green_button_intervals_analytics_v i
  where i.duration_seconds > 0
),
dedup_usage_point_interval as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_local)::date as month_start,
    date(interval_start_local) as local_day,
    interval_start_local,
    source_usage_point_id,
    max(kw)::numeric(18,6) as usage_point_kw
  from interval_points
  group by
    org_id,
    building_id,
    date_trunc('month', interval_start_local)::date,
    date(interval_start_local),
    interval_start_local,
    source_usage_point_id
),
building_interval as (
  select
    org_id,
    building_id,
    month_start,
    local_day,
    interval_start_local,
    extract(isodow from interval_start_local)::int as isodow,
    extract(hour from interval_start_local)::int as hour_local,
    extract(minute from interval_start_local)::int as minute_local,
    sum(usage_point_kw)::numeric(18,6) as building_kw
  from dedup_usage_point_interval
  group by org_id, building_id, month_start, local_day, interval_start_local
),
two_am_points as (
  select
    org_id,
    building_id,
    month_start,
    building_kw
  from building_interval
  where isodow between 1 and 5
    and hour_local = 2
    and minute_local = 0
),
daily_peaks as (
  select
    org_id,
    building_id,
    month_start,
    local_day,
    max(building_kw)::numeric(18,6) as daily_peak_kw
  from building_interval
  where isodow between 1 and 5
  group by org_id, building_id, month_start, local_day
),
two_am_agg as (
  select
    org_id,
    building_id,
    month_start,
    avg(building_kw)::numeric(18,6) as avg_2am_kw_weekdays,
    count(*)::integer as two_am_intervals_count
  from two_am_points
  group by org_id, building_id, month_start
),
daily_peak_agg as (
  select
    org_id,
    building_id,
    month_start,
    max(daily_peak_kw)::numeric(18,6) as peak_weekday_kw
  from daily_peaks
  group by org_id, building_id, month_start
)
select
  t.org_id,
  t.building_id,
  t.month_start,
  t.avg_2am_kw_weekdays,
  p.peak_weekday_kw,
  t.two_am_intervals_count
from two_am_agg t
join daily_peak_agg p
  on p.org_id = t.org_id
 and p.building_id = t.building_id
 and p.month_start = t.month_start;

create unique index if not exists green_button_after_hours_pct_monthly_mv_uidx
  on public.green_button_after_hours_pct_monthly_mv (org_id, building_id, month_start);

create index if not exists green_button_after_hours_pct_monthly_mv_org_month_idx
  on public.green_button_after_hours_pct_monthly_mv (org_id, month_start desc);

create or replace function public.refresh_green_button_after_hours_pct_monthly_mv()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows bigint := 0;
begin
  perform set_config('statement_timeout', '0', true);
  refresh materialized view public.green_button_after_hours_pct_monthly_mv;

  select count(*)::bigint
    into v_rows
  from public.green_button_after_hours_pct_monthly_mv;

  return jsonb_build_object(
    'rows_refreshed', v_rows,
    'timezone', 'stored interval clock basis (interval_start_utc at time zone UTC)'
  );
end;
$$;

create table if not exists public.green_button_load_shape_monthly_history (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  month_start date not null,
  slot_index smallint not null check (slot_index >= 0 and slot_index <= 95),
  hhmm text not null,
  avg_kw numeric(18,6) not null check (avg_kw >= 0),
  intervals_count integer not null check (intervals_count >= 0),
  weekday_days_count integer not null check (weekday_days_count >= 0),
  source text not null default 'archived',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint green_button_load_shape_monthly_history_unique
    unique (org_id, building_id, month_start, slot_index)
);

create index if not exists green_button_load_shape_monthly_history_org_month_idx
  on public.green_button_load_shape_monthly_history (org_id, month_start desc);

drop materialized view if exists public.green_button_load_shape_monthly_mv;

create materialized view public.green_button_load_shape_monthly_mv as
with interval_points as (
  select
    i.org_id,
    i.building_id,
    i.interval_start_utc,
    i.interval_start_utc at time zone 'UTC' as interval_start_local,
    max(i.duration_seconds)::integer as duration_seconds,
    sum(i.value_wh)::numeric(18,6) as value_wh
  from public.green_button_intervals_analytics_v i
  where i.duration_seconds > 0
  group by
    i.org_id,
    i.building_id,
    i.interval_start_utc
),
weekday_points as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_local)::date as month_start,
    date(interval_start_local) as local_day,
    extract(hour from interval_start_local)::integer as local_hour,
    floor(extract(minute from interval_start_local) / 15.0)::integer as quarter_hour,
    (value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0 as kw
  from interval_points
  where extract(isodow from interval_start_local) between 1 and 5
),
raw_monthly as (
  select
    org_id,
    building_id,
    month_start,
    (local_hour * 4 + quarter_hour)::smallint as slot_index,
    lpad(local_hour::text, 2, '0') || ':' || lpad((quarter_hour * 15)::text, 2, '0') as hhmm,
    avg(kw)::numeric(18,6) as avg_kw,
    count(*)::integer as intervals_count,
    count(distinct local_day)::integer as weekday_days_count
  from weekday_points
  where quarter_hour between 0 and 3
  group by org_id, building_id, month_start, local_hour, quarter_hour
),
combined as (
  select
    org_id,
    building_id,
    month_start,
    slot_index,
    hhmm,
    avg_kw,
    intervals_count,
    weekday_days_count,
    2 as source_rank
  from raw_monthly
  union all
  select
    org_id,
    building_id,
    month_start,
    slot_index,
    hhmm,
    avg_kw,
    intervals_count,
    weekday_days_count,
    1 as source_rank
  from public.green_button_load_shape_monthly_history
),
final_ranked as (
  select
    org_id,
    building_id,
    month_start,
    slot_index,
    hhmm,
    avg_kw,
    intervals_count,
    weekday_days_count,
    row_number() over (
      partition by org_id, building_id, month_start, slot_index
      order by source_rank desc
    ) as rn
  from combined
)
select
  org_id,
  building_id,
  month_start,
  slot_index,
  hhmm,
  avg_kw,
  intervals_count,
  weekday_days_count
from final_ranked
where rn = 1;

create unique index if not exists green_button_load_shape_monthly_mv_uidx
  on public.green_button_load_shape_monthly_mv (org_id, building_id, month_start, slot_index);

create index if not exists green_button_load_shape_monthly_mv_org_month_idx
  on public.green_button_load_shape_monthly_mv (org_id, month_start desc);

create or replace function public.refresh_green_button_load_shape_monthly_mv()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows bigint := 0;
begin
  perform set_config('statement_timeout', '0', true);
  refresh materialized view public.green_button_load_shape_monthly_mv;

  select count(*)::bigint
    into v_rows
  from public.green_button_load_shape_monthly_mv;

  return jsonb_build_object(
    'rows_refreshed', v_rows,
    'timezone', 'stored interval clock basis (interval_start_utc at time zone UTC)'
  );
end;
$$;

create or replace function public.refresh_green_button_load_shape_monthly_mv_checked(
  p_org_id uuid,
  p_building_id uuid,
  p_month_starts date[] default null,
  p_expected_weekday_intervals integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows_refreshed bigint := 0;
  v_rows_for_scope bigint := 0;
  v_retry_used boolean := false;
  v_verified boolean := true;
  v_months_checked date[];
begin
  perform set_config('statement_timeout', '0', true);
  refresh materialized view public.green_button_load_shape_monthly_mv;

  select count(*)::bigint
    into v_rows_refreshed
  from public.green_button_load_shape_monthly_mv;

  v_months_checked := (
    select array_agg(distinct m)::date[]
    from (
      select unnest(coalesce(p_month_starts, array[]::date[])) as m
      union all
      select (unnest(coalesce(p_month_starts, array[]::date[])) - interval '1 month')::date as m
    ) s
    where m is not null
  );

  if coalesce(array_length(v_months_checked, 1), 0) > 0 and coalesce(p_expected_weekday_intervals, 0) > 0 then
    select count(*)::bigint
      into v_rows_for_scope
    from public.green_button_load_shape_monthly_mv
    where org_id = p_org_id
      and building_id = p_building_id
      and month_start = any(v_months_checked);

    if v_rows_for_scope = 0 then
      v_retry_used := true;
      refresh materialized view public.green_button_load_shape_monthly_mv;

      select count(*)::bigint
        into v_rows_for_scope
      from public.green_button_load_shape_monthly_mv
      where org_id = p_org_id
        and building_id = p_building_id
        and month_start = any(v_months_checked);
    end if;

    v_verified := v_rows_for_scope > 0;
  end if;

  return jsonb_build_object(
    'rows_refreshed', v_rows_refreshed,
    'rows_for_scope', v_rows_for_scope,
    'months_checked', coalesce(v_months_checked, array[]::date[]),
    'expected_weekday_intervals', coalesce(p_expected_weekday_intervals, 0),
    'retry_used', v_retry_used,
    'verified', v_verified,
    'timezone', 'UTC'
  );
end;
$$;

create table if not exists public.green_button_load_shape_monthly_cache (
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  month_start date not null,
  slot_index smallint not null check (slot_index >= 0 and slot_index <= 95),
  hhmm text not null,
  avg_kw numeric(18,6) not null check (avg_kw >= 0),
  intervals_count integer not null default 0 check (intervals_count >= 0),
  weekday_days_count integer not null default 0 check (weekday_days_count >= 0),
  refreshed_at timestamptz not null default now(),
  primary key (org_id, building_id, month_start, slot_index)
);

create index if not exists green_button_load_shape_monthly_cache_org_month_idx
  on public.green_button_load_shape_monthly_cache (org_id, month_start desc);

create or replace function public.refresh_green_button_load_shape_monthly_cache_scoped(
  p_org_id uuid,
  p_building_id uuid default null,
  p_month_starts date[] default null,
  p_expected_weekday_intervals integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows_upserted bigint := 0;
  v_rows_for_scope bigint := 0;
  v_verified boolean := true;
  v_months_checked date[];
begin
  if p_org_id is null then
    raise exception 'p_org_id is required';
  end if;

  v_months_checked := (
    select array_agg(distinct m)::date[]
    from (
      select unnest(coalesce(p_month_starts, array[]::date[])) as m
      union all
      select (unnest(coalesce(p_month_starts, array[]::date[])) - interval '1 month')::date as m
    ) s
    where m is not null
  );

  delete from public.green_button_load_shape_monthly_cache c
  where c.org_id = p_org_id
    and (p_building_id is null or c.building_id = p_building_id)
    and (
      coalesce(array_length(v_months_checked, 1), 0) = 0
      or c.month_start = any(v_months_checked)
    );

  with interval_points as (
    select
      i.org_id,
      i.building_id,
      i.interval_start_utc,
      i.interval_start_utc at time zone 'UTC' as interval_start_local,
      max(i.duration_seconds)::integer as duration_seconds,
      sum(i.value_wh)::numeric(18,6) as value_wh
    from public.green_button_intervals_analytics_v i
    where i.org_id = p_org_id
      and (p_building_id is null or i.building_id = p_building_id)
      and i.duration_seconds > 0
    group by
      i.org_id,
      i.building_id,
      i.interval_start_utc
  ),
  weekday_points as (
    select
      org_id,
      building_id,
      date_trunc('month', interval_start_local)::date as month_start,
      date(interval_start_local) as local_day,
      extract(hour from interval_start_local)::integer as local_hour,
      floor(extract(minute from interval_start_local) / 15.0)::integer as quarter_hour,
      (value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0 as kw
    from interval_points
    where extract(isodow from interval_start_local) between 1 and 5
  ),
  raw_monthly as (
    select
      org_id,
      building_id,
      month_start,
      (local_hour * 4 + quarter_hour)::smallint as slot_index,
      lpad(local_hour::text, 2, '0') || ':' || lpad((quarter_hour * 15)::text, 2, '0') as hhmm,
      avg(kw)::numeric(18,6) as avg_kw,
      count(*)::integer as intervals_count,
      count(distinct local_day)::integer as weekday_days_count
    from weekday_points
    where quarter_hour between 0 and 3
      and (
        coalesce(array_length(v_months_checked, 1), 0) = 0
        or month_start = any(v_months_checked)
      )
    group by org_id, building_id, month_start, local_hour, quarter_hour
  ),
  combined as (
    select
      org_id,
      building_id,
      month_start,
      slot_index,
      hhmm,
      avg_kw,
      intervals_count,
      weekday_days_count,
      2 as source_rank
    from raw_monthly
    union all
    select
      h.org_id,
      h.building_id,
      h.month_start,
      h.slot_index,
      h.hhmm,
      h.avg_kw,
      h.intervals_count,
      h.weekday_days_count,
      1 as source_rank
    from public.green_button_load_shape_monthly_history h
    where h.org_id = p_org_id
      and (p_building_id is null or h.building_id = p_building_id)
      and (
        coalesce(array_length(v_months_checked, 1), 0) = 0
        or h.month_start = any(v_months_checked)
      )
  ),
  final_ranked as (
    select
      org_id,
      building_id,
      month_start,
      slot_index,
      hhmm,
      avg_kw,
      intervals_count,
      weekday_days_count,
      row_number() over (
        partition by org_id, building_id, month_start, slot_index
        order by source_rank desc
      ) as rn
    from combined
  ),
  scoped_rows as (
    select
      org_id,
      building_id,
      month_start,
      slot_index,
      hhmm,
      avg_kw,
      intervals_count,
      weekday_days_count
    from final_ranked
    where rn = 1
  )
  insert into public.green_button_load_shape_monthly_cache (
    org_id,
    building_id,
    month_start,
    slot_index,
    hhmm,
    avg_kw,
    intervals_count,
    weekday_days_count,
    refreshed_at
  )
  select
    org_id,
    building_id,
    month_start,
    slot_index,
    hhmm,
    avg_kw,
    intervals_count,
    weekday_days_count,
    now()
  from scoped_rows
  on conflict (org_id, building_id, month_start, slot_index)
  do update set
    hhmm = excluded.hhmm,
    avg_kw = excluded.avg_kw,
    intervals_count = excluded.intervals_count,
    weekday_days_count = excluded.weekday_days_count,
    refreshed_at = excluded.refreshed_at;

  get diagnostics v_rows_upserted = row_count;

  if coalesce(array_length(v_months_checked, 1), 0) > 0 and coalesce(p_expected_weekday_intervals, 0) > 0 then
    select count(*)::bigint
      into v_rows_for_scope
    from public.green_button_load_shape_monthly_cache
    where org_id = p_org_id
      and (p_building_id is null or building_id = p_building_id)
      and month_start = any(v_months_checked);

    v_verified := v_rows_for_scope > 0;
  end if;

  return jsonb_build_object(
    'rows_upserted', v_rows_upserted,
    'rows_for_scope', v_rows_for_scope,
    'months_checked', coalesce(v_months_checked, array[]::date[]),
    'expected_weekday_intervals', coalesce(p_expected_weekday_intervals, 0),
    'verified', v_verified,
    'cache_table', 'green_button_load_shape_monthly_cache'
  );
end;
$$;

grant select on public.green_button_load_shape_monthly_cache to authenticated;
grant execute on function public.refresh_green_button_load_shape_monthly_cache_scoped(uuid, uuid, date[], integer) to authenticated;
grant execute on function public.refresh_green_button_load_shape_monthly_cache_scoped(uuid, uuid, date[], integer) to service_role;

create table if not exists public.green_button_weekend_ops_monthly_history (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  month_start date not null,
  weekend_kwh_avg numeric(18,6) null check (weekend_kwh_avg >= 0),
  weekday_kwh_avg numeric(18,6) null check (weekday_kwh_avg >= 0),
  weekend_days_count integer not null default 0 check (weekend_days_count >= 0),
  weekday_days_count integer not null default 0 check (weekday_days_count >= 0),
  source text not null default 'archived',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint green_button_weekend_ops_monthly_history_unique
    unique (org_id, building_id, month_start)
);

create index if not exists green_button_weekend_ops_monthly_history_org_month_idx
  on public.green_button_weekend_ops_monthly_history (org_id, month_start desc);

drop materialized view if exists public.green_button_weekend_ops_monthly_mv;

create materialized view public.green_button_weekend_ops_monthly_mv as
with interval_points as (
  select
    i.org_id,
    i.building_id,
    i.interval_start_utc at time zone 'UTC' as interval_start_local,
    i.value_wh / 1000.0 as kwh
  from public.green_button_intervals_analytics_v i
  where i.duration_seconds > 0
),
daily_totals as (
  select
    org_id,
    building_id,
    date_trunc('month', interval_start_local)::date as month_start,
    date(interval_start_local) as local_day,
    sum(kwh)::numeric(18,6) as day_kwh
  from interval_points
  group by org_id, building_id, date_trunc('month', interval_start_local), date(interval_start_local)
),
raw_monthly as (
  select
    org_id,
    building_id,
    month_start,
    avg(day_kwh) filter (where extract(isodow from local_day) in (6, 7))::numeric(18,6) as weekend_kwh_avg,
    avg(day_kwh) filter (where extract(isodow from local_day) between 1 and 5)::numeric(18,6) as weekday_kwh_avg,
    count(*) filter (where extract(isodow from local_day) in (6, 7))::integer as weekend_days_count,
    count(*) filter (where extract(isodow from local_day) between 1 and 5)::integer as weekday_days_count
  from daily_totals
  group by org_id, building_id, month_start
),
combined as (
  select
    org_id,
    building_id,
    month_start,
    weekend_kwh_avg,
    weekday_kwh_avg,
    weekend_days_count,
    weekday_days_count,
    2 as source_rank
  from raw_monthly
  union all
  select
    org_id,
    building_id,
    month_start,
    weekend_kwh_avg,
    weekday_kwh_avg,
    weekend_days_count,
    weekday_days_count,
    1 as source_rank
  from public.green_button_weekend_ops_monthly_history
),
final_ranked as (
  select
    org_id,
    building_id,
    month_start,
    weekend_kwh_avg,
    weekday_kwh_avg,
    weekend_days_count,
    weekday_days_count,
    row_number() over (
      partition by org_id, building_id, month_start
      order by source_rank desc
    ) as rn
  from combined
)
select
  org_id,
  building_id,
  month_start,
  weekend_kwh_avg,
  weekday_kwh_avg,
  weekend_days_count,
  weekday_days_count
from final_ranked
where rn = 1;

create unique index if not exists green_button_weekend_ops_monthly_mv_uidx
  on public.green_button_weekend_ops_monthly_mv (org_id, building_id, month_start);

create index if not exists green_button_weekend_ops_monthly_mv_org_month_idx
  on public.green_button_weekend_ops_monthly_mv (org_id, month_start desc);

create or replace function public.refresh_green_button_weekend_ops_monthly_mv()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows bigint := 0;
begin
  perform set_config('statement_timeout', '0', true);
  refresh materialized view public.green_button_weekend_ops_monthly_mv;

  select count(*)::bigint
    into v_rows
  from public.green_button_weekend_ops_monthly_mv;

  return jsonb_build_object(
    'rows_refreshed', v_rows,
    'timezone', 'stored interval clock basis (interval_start_utc at time zone UTC)'
  );
end;
$$;

drop materialized view if exists public.green_button_demand_facts_monthly_mv;

create materialized view public.green_button_demand_facts_monthly_mv as
with normalized as (
  select
    b.org_id,
    bm.building_id,
    date_trunc('month', bm.bill_month)::date as month_start,
    bm.adjusted_demand_kw,
    bm.tariff_min_kw,
    bm.ratchet_kw,
    bm.billing_demand_kw,
    bm.demand_charge_usd
  from public.bill_months bm
  join public.buildings b
    on b.id = bm.building_id
  where bm.bill_month is not null
    and bm.building_id is not null
),
aggregated as (
  select
    org_id,
    building_id,
    month_start,
    max(adjusted_demand_kw)::numeric(18,6) as adjusted_demand_kw,
    max(tariff_min_kw)::numeric(18,6) as tariff_min_kw,
    max(ratchet_kw)::numeric(18,6) as ratchet_kw,
    max(billing_demand_kw)::numeric(18,6) as billing_demand_kw,
    sum(demand_charge_usd)::numeric(18,6) as demand_charge_usd_total,
    sum(billing_demand_kw) filter (where billing_demand_kw > 0 and demand_charge_usd is not null)::numeric(18,6)
      as billing_demand_kw_for_rate
  from normalized
  group by org_id, building_id, month_start
)
select
  org_id,
  building_id,
  month_start,
  adjusted_demand_kw,
  tariff_min_kw,
  ratchet_kw,
  billing_demand_kw,
  demand_charge_usd_total,
  case
    when billing_demand_kw_for_rate > 0
      then (demand_charge_usd_total / billing_demand_kw_for_rate)::numeric(18,6)
    else null
  end as effective_demand_rate_usd_per_kw
from aggregated;

create unique index if not exists green_button_demand_facts_monthly_mv_uidx
  on public.green_button_demand_facts_monthly_mv (org_id, building_id, month_start);

create index if not exists green_button_demand_facts_monthly_mv_org_month_idx
  on public.green_button_demand_facts_monthly_mv (org_id, month_start desc);

create or replace function public.refresh_green_button_demand_facts_monthly_mv()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows bigint := 0;
begin
  perform set_config('statement_timeout', '0', true);
  refresh materialized view public.green_button_demand_facts_monthly_mv;

  select count(*)::bigint
    into v_rows
  from public.green_button_demand_facts_monthly_mv;

  return jsonb_build_object(
    'rows_refreshed', v_rows
  );
end;
$$;

grant select on public.green_button_demand_facts_monthly_mv to authenticated;
grant execute on function public.refresh_green_button_demand_facts_monthly_mv() to authenticated;
grant execute on function public.refresh_green_button_demand_facts_monthly_mv() to service_role;
grant select on public.green_button_after_hours_pct_monthly_mv to authenticated;
grant execute on function public.refresh_green_button_after_hours_pct_monthly_mv() to authenticated;
grant execute on function public.refresh_green_button_after_hours_pct_monthly_mv() to service_role;

create or replace view public.green_button_monthly_peak_kw_v as
with raw_ranked as (
  select
    i.org_id,
    i.building_id,
    date_trunc(
      'month',
      i.interval_start_utc at time zone 'UTC'
    )::date as month_start,
    i.interval_start_utc,
    (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 as peak_kw,
    row_number() over (
      partition by
        i.org_id,
        i.building_id,
        date_trunc(
          'month',
          i.interval_start_utc at time zone 'UTC'
        )
      order by
        (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 desc,
        i.interval_start_utc desc
    ) as rn
  from public.green_button_intervals_analytics_v i
  left join public.buildings b
    on b.id = i.building_id
  where i.duration_seconds > 0
),
raw_monthly as (
  select
    org_id,
    building_id,
    month_start,
    peak_kw,
    interval_start_utc as peak_interval_start_utc
  from raw_ranked
  where rn = 1
),
combined as (
  select org_id, building_id, month_start, peak_kw, peak_interval_start_utc from raw_monthly
  union all
  select org_id, building_id, month_start, peak_kw, peak_interval_start_utc
  from public.green_button_monthly_peak_history
),
final_ranked as (
  select
    org_id,
    building_id,
    month_start,
    peak_kw,
    peak_interval_start_utc,
    row_number() over (
      partition by org_id, building_id, month_start
      order by peak_kw desc, peak_interval_start_utc desc nulls last
    ) as rn
  from combined
)
select
  org_id,
  building_id,
  month_start,
  peak_kw,
  peak_interval_start_utc
from final_ranked
where rn = 1;

create or replace function public.archive_and_prune_green_button_intervals(
  p_org_id uuid,
  p_keep_months integer default 13
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cutoff timestamptz;
  v_deleted bigint := 0;
  v_upserted bigint := 0;
  v_energy_upserted bigint := 0;
  v_startup_upserted bigint := 0;
  v_peak_timing_upserted bigint := 0;
  v_after_hours_upserted bigint := 0;
  v_load_shape_upserted bigint := 0;
  v_top_peaks_upserted bigint := 0;
  v_weekend_ops_upserted bigint := 0;
begin
  if p_keep_months < 1 then
    raise exception 'p_keep_months must be >= 1';
  end if;

  v_cutoff := date_trunc('month', now()) - make_interval(months => p_keep_months);

  with old_ranked as (
    select
      i.org_id,
      i.building_id,
      date_trunc(
        'month',
        i.interval_start_utc at time zone 'UTC'
      )::date as month_start,
      i.interval_start_utc,
      (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 as peak_kw,
      row_number() over (
        partition by
          i.org_id,
          i.building_id,
          date_trunc(
            'month',
            i.interval_start_utc at time zone 'UTC'
          )
        order by
          (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 desc,
          i.interval_start_utc desc
      ) as rn
    from public.green_button_intervals_analytics_v i
    left join public.buildings b
      on b.id = i.building_id
    where i.org_id = p_org_id
      and i.interval_start_utc < v_cutoff
      and i.duration_seconds > 0
  ),
  old_monthly as (
    select
      org_id,
      building_id,
      month_start,
      peak_kw,
      interval_start_utc as peak_interval_start_utc
    from old_ranked
    where rn = 1
  ),
  upserted as (
    insert into public.green_button_monthly_peak_history (
      org_id, building_id, month_start, peak_kw, peak_interval_start_utc, source, updated_at
    )
    select
      org_id, building_id, month_start, peak_kw, peak_interval_start_utc, 'archived', now()
    from old_monthly
    on conflict (org_id, building_id, month_start) do update
      set peak_kw = excluded.peak_kw,
          peak_interval_start_utc = excluded.peak_interval_start_utc,
          source = 'archived',
          updated_at = now()
    returning 1
  ),
  old_energy_monthly as (
    select
      org_id,
      building_id,
      date_trunc('month', interval_start_utc)::date as month_start,
      sum(value_wh) / 1000.0 as kwh_total
    from public.green_button_intervals_analytics_v
    where org_id = p_org_id
      and interval_start_utc < v_cutoff
      and duration_seconds > 0
    group by org_id, building_id, date_trunc('month', interval_start_utc)
  ),
  energy_upserted as (
    insert into public.green_button_monthly_energy_history (
      org_id,
      building_id,
      month_start,
      kwh_total,
      source,
      updated_at
    )
    select
      org_id,
      building_id,
      month_start,
      kwh_total,
      'archived',
      now()
    from old_energy_monthly
    on conflict (org_id, building_id, month_start) do update
      set kwh_total = excluded.kwh_total,
          source = 'archived',
          updated_at = now()
    returning 1
  ),
  old_startup_points as (
    select
      i.org_id,
      i.building_id,
      i.interval_start_utc,
      i.interval_start_utc at time zone 'UTC' as interval_start_local,
      (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 as kw
    from public.green_button_intervals_analytics_v i
    left join public.buildings b
      on b.id = i.building_id
    where i.org_id = p_org_id
      and i.interval_start_utc < v_cutoff
      and i.duration_seconds > 0
  ),
  old_startup_ranked as (
    select
      org_id,
      building_id,
      date_trunc('month', interval_start_local)::date as month_start,
      interval_start_utc as ramp_interval_start_utc,
      interval_start_local as ramp_interval_start_local,
      kw - lag(kw) over (
        partition by org_id, building_id
        order by interval_start_utc
      ) as ramp_kw
    from old_startup_points
  ),
  old_startup_monthly as (
    select
      org_id,
      building_id,
      month_start,
      ramp_kw as max_ramp_kw,
      ramp_interval_start_utc,
      row_number() over (
        partition by org_id, building_id, month_start
        order by ramp_kw desc, ramp_interval_start_utc desc
      ) as rn
    from old_startup_ranked
    where extract(hour from ramp_interval_start_local) >= 4
      and extract(hour from ramp_interval_start_local) < 9
      and ramp_kw is not null
      and ramp_kw > 0
  ),
  startup_upserted as (
    insert into public.green_button_startup_intensity_monthly_history (
      org_id,
      building_id,
      month_start,
      max_ramp_kw,
      ramp_interval_start_utc,
      source,
      updated_at
    )
    select
      org_id,
      building_id,
      month_start,
      max_ramp_kw,
      ramp_interval_start_utc,
      'archived',
      now()
    from old_startup_monthly
    where rn = 1
    on conflict (org_id, building_id, month_start) do update
      set max_ramp_kw = excluded.max_ramp_kw,
          ramp_interval_start_utc = excluded.ramp_interval_start_utc,
          source = 'archived',
          updated_at = now()
    returning 1
  ),
  old_peak_timing_points as (
    select
      i.org_id,
      i.building_id,
      i.interval_start_utc,
      i.interval_start_utc at time zone 'UTC' as interval_start_local,
      (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 as kw
    from public.green_button_intervals_analytics_v i
    left join public.buildings b
      on b.id = i.building_id
    where i.org_id = p_org_id
      and i.interval_start_utc < v_cutoff
      and i.duration_seconds > 0
  ),
  old_peak_timing_ranked as (
    select
      org_id,
      building_id,
      date_trunc('month', interval_start_local)::date as month_start,
      extract(hour from interval_start_local)::integer as peak_hour_local,
      row_number() over (
        partition by org_id, building_id, date(interval_start_local)
        order by kw desc, interval_start_utc desc
      ) as rn
    from old_peak_timing_points
  ),
  old_peak_timing_histogram as (
    select
      org_id,
      building_id,
      month_start,
      peak_hour_local,
      count(*)::integer as daily_peak_count
    from old_peak_timing_ranked
    where rn = 1
    group by org_id, building_id, month_start, peak_hour_local
  ),
  peak_timing_upserted as (
    insert into public.green_button_peak_timing_monthly_history (
      org_id,
      building_id,
      month_start,
      peak_hour_local,
      daily_peak_count,
      source,
      updated_at
    )
    select
      org_id,
      building_id,
      month_start,
      peak_hour_local,
      daily_peak_count,
      'archived',
      now()
    from old_peak_timing_histogram
    on conflict (org_id, building_id, month_start, peak_hour_local) do update
      set daily_peak_count = excluded.daily_peak_count,
          source = 'archived',
          updated_at = now()
    returning 1
  ),
  old_after_hours_points as (
    select
      i.org_id,
      i.building_id,
      date_trunc(
        'month',
        i.interval_start_utc at time zone 'UTC'
      )::date as month_start,
      date(
        i.interval_start_utc at time zone 'UTC'
      ) as local_day,
      (i.value_wh * 3600.0) / nullif(i.duration_seconds, 0) / 1000.0 as kw,
      i.interval_start_utc
    from public.green_button_intervals_analytics_v i
    left join public.buildings b
      on b.id = i.building_id
    where i.org_id = p_org_id
      and i.interval_start_utc < v_cutoff
      and i.duration_seconds > 0
      and (
        extract(
          hour from (
            i.interval_start_utc at time zone 'UTC'
          )
        ) >= 22
        or extract(
          hour from (
            i.interval_start_utc at time zone 'UTC'
          )
        ) < 4
      )
  ),
  old_after_hours_daily_mins as (
    select
      org_id,
      building_id,
      month_start,
      local_day,
      kw as night_min_kw,
      row_number() over (
        partition by org_id, building_id, local_day
        order by kw asc, interval_start_utc desc
      ) as rn
    from old_after_hours_points
    where kw > 0
  ),
  old_after_hours_monthly as (
    select
      org_id,
      building_id,
      month_start,
      avg(night_min_kw)::numeric(18,6) as avg_night_min_kw,
      count(*)::integer as nights_count
    from old_after_hours_daily_mins
    where rn = 1
    group by org_id, building_id, month_start
  ),
  after_hours_upserted as (
    insert into public.green_button_after_hours_load_monthly_history (
      org_id,
      building_id,
      month_start,
      avg_night_min_kw,
      nights_count,
      source,
      updated_at
    )
    select
      org_id,
      building_id,
      month_start,
      avg_night_min_kw,
      nights_count,
      'archived',
      now()
    from old_after_hours_monthly
    on conflict (org_id, building_id, month_start) do update
      set avg_night_min_kw = excluded.avg_night_min_kw,
          nights_count = excluded.nights_count,
          source = 'archived',
          updated_at = now()
    returning 1
  ),
  old_load_shape_points as (
    select
      i.org_id,
      i.building_id,
      date_trunc(
        'month',
        i.interval_start_utc at time zone 'UTC'
      )::date as month_start,
      date(
        i.interval_start_utc at time zone 'UTC'
      ) as local_day,
      extract(
        hour from (
          i.interval_start_utc at time zone 'UTC'
        )
      )::integer as local_hour,
      floor(
        extract(
          minute from (
            i.interval_start_utc at time zone 'UTC'
          )
        ) / 15.0
      )::integer as quarter_hour,
      max(i.duration_seconds)::integer as duration_seconds,
      sum(i.value_wh)::numeric(18,6) as value_wh
    from public.green_button_intervals_analytics_v i
    left join public.buildings b
      on b.id = i.building_id
    where i.org_id = p_org_id
      and i.interval_start_utc < v_cutoff
      and i.duration_seconds > 0
      and extract(
        isodow from (
          i.interval_start_utc at time zone 'UTC'
        )
      ) between 1 and 5
    group by
      i.org_id,
      i.building_id,
      date_trunc(
        'month',
        i.interval_start_utc at time zone 'UTC'
      )::date,
      date(i.interval_start_utc at time zone 'UTC'),
      extract(
        hour from (
          i.interval_start_utc at time zone 'UTC'
        )
      )::integer,
      floor(
        extract(
          minute from (
            i.interval_start_utc at time zone 'UTC'
          )
        ) / 15.0
      )::integer
  ),
  old_load_shape_monthly as (
    select
      org_id,
      building_id,
      month_start,
      (local_hour * 4 + quarter_hour)::smallint as slot_index,
      lpad(local_hour::text, 2, '0') || ':' || lpad((quarter_hour * 15)::text, 2, '0') as hhmm,
      avg((value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0)::numeric(18,6) as avg_kw,
      count(*)::integer as intervals_count,
      count(distinct local_day)::integer as weekday_days_count
    from old_load_shape_points
    where quarter_hour between 0 and 3
    group by org_id, building_id, month_start, local_hour, quarter_hour
  ),
  load_shape_upserted as (
    insert into public.green_button_load_shape_monthly_history (
      org_id,
      building_id,
      month_start,
      slot_index,
      hhmm,
      avg_kw,
      intervals_count,
      weekday_days_count,
      source,
      updated_at
    )
    select
      org_id,
      building_id,
      month_start,
      slot_index,
      hhmm,
      avg_kw,
      intervals_count,
      weekday_days_count,
      'archived',
      now()
    from old_load_shape_monthly
    on conflict (org_id, building_id, month_start, slot_index) do update
      set hhmm = excluded.hhmm,
          avg_kw = excluded.avg_kw,
          intervals_count = excluded.intervals_count,
          weekday_days_count = excluded.weekday_days_count,
          source = 'archived',
          updated_at = now()
    returning 1
  ),
  old_top_ranked as (
    select
      org_id,
      building_id,
      date_trunc('month', interval_start_utc)::date as month_start,
      (value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0 as peak_kw,
      interval_start_utc as peak_interval_start_utc,
      row_number() over (
        partition by org_id, building_id, date_trunc('month', interval_start_utc)
        order by
          (value_wh * 3600.0) / nullif(duration_seconds, 0) / 1000.0 desc,
          interval_start_utc desc
      ) as peak_rank
    from public.green_button_intervals_analytics_v
    where org_id = p_org_id
      and interval_start_utc < v_cutoff
      and duration_seconds > 0
  ),
  old_top_monthly as (
    select
      org_id,
      building_id,
      month_start,
      peak_rank,
      peak_kw,
      peak_interval_start_utc
    from old_top_ranked
    where peak_rank <= 5
  ),
  top_peaks_upserted as (
    insert into public.green_button_monthly_top_peaks_history (
      org_id,
      building_id,
      month_start,
      peak_rank,
      peak_kw,
      peak_interval_start_utc,
      source,
      updated_at
    )
    select
      org_id,
      building_id,
      month_start,
      peak_rank,
      peak_kw,
      peak_interval_start_utc,
      'archived',
      now()
    from old_top_monthly
    on conflict (org_id, building_id, month_start, peak_rank) do update
      set peak_kw = excluded.peak_kw,
          peak_interval_start_utc = excluded.peak_interval_start_utc,
          source = 'archived',
          updated_at = now()
    returning 1
  ),
  old_weekend_points as (
    select
      i.org_id,
      i.building_id,
      i.interval_start_utc at time zone 'UTC' as interval_start_local,
      i.value_wh / 1000.0 as kwh
    from public.green_button_intervals_analytics_v i
    left join public.buildings b
      on b.id = i.building_id
    where i.org_id = p_org_id
      and i.interval_start_utc < v_cutoff
      and i.duration_seconds > 0
  ),
  old_weekend_daily_totals as (
    select
      org_id,
      building_id,
      date_trunc('month', interval_start_local)::date as month_start,
      date(interval_start_local) as local_day,
      sum(kwh)::numeric(18,6) as day_kwh
    from old_weekend_points
    group by org_id, building_id, date_trunc('month', interval_start_local), date(interval_start_local)
  ),
  old_weekend_monthly as (
    select
      org_id,
      building_id,
      month_start,
      avg(day_kwh) filter (where extract(isodow from local_day) in (6, 7))::numeric(18,6) as weekend_kwh_avg,
      avg(day_kwh) filter (where extract(isodow from local_day) between 1 and 5)::numeric(18,6) as weekday_kwh_avg,
      count(*) filter (where extract(isodow from local_day) in (6, 7))::integer as weekend_days_count,
      count(*) filter (where extract(isodow from local_day) between 1 and 5)::integer as weekday_days_count
    from old_weekend_daily_totals
    group by org_id, building_id, month_start
  ),
  weekend_ops_upserted as (
    insert into public.green_button_weekend_ops_monthly_history (
      org_id,
      building_id,
      month_start,
      weekend_kwh_avg,
      weekday_kwh_avg,
      weekend_days_count,
      weekday_days_count,
      source,
      updated_at
    )
    select
      org_id,
      building_id,
      month_start,
      weekend_kwh_avg,
      weekday_kwh_avg,
      weekend_days_count,
      weekday_days_count,
      'archived',
      now()
    from old_weekend_monthly
    on conflict (org_id, building_id, month_start) do update
      set weekend_kwh_avg = excluded.weekend_kwh_avg,
          weekday_kwh_avg = excluded.weekday_kwh_avg,
          weekend_days_count = excluded.weekend_days_count,
          weekday_days_count = excluded.weekday_days_count,
          source = 'archived',
          updated_at = now()
    returning 1
  )
  select
    (select count(*)::bigint from upserted),
    (select count(*)::bigint from energy_upserted),
    (select count(*)::bigint from startup_upserted),
    (select count(*)::bigint from peak_timing_upserted),
    (select count(*)::bigint from after_hours_upserted),
    (select count(*)::bigint from load_shape_upserted),
    (select count(*)::bigint from top_peaks_upserted),
    (select count(*)::bigint from weekend_ops_upserted)
  into v_upserted, v_energy_upserted, v_startup_upserted, v_peak_timing_upserted, v_after_hours_upserted, v_load_shape_upserted, v_top_peaks_upserted, v_weekend_ops_upserted;

  delete from public.green_button_intervals
  where org_id = p_org_id
    and interval_start_utc < v_cutoff;

  get diagnostics v_deleted = row_count;

  return jsonb_build_object(
    'org_id', p_org_id,
    'cutoff_utc', v_cutoff,
    'months_kept', p_keep_months,
    'history_upserted', v_upserted,
    'energy_history_upserted', v_energy_upserted,
    'startup_history_upserted', v_startup_upserted,
    'peak_timing_history_upserted', v_peak_timing_upserted,
    'after_hours_history_upserted', v_after_hours_upserted,
    'load_shape_history_upserted', v_load_shape_upserted,
    'top_peaks_history_upserted', v_top_peaks_upserted,
    'weekend_ops_history_upserted', v_weekend_ops_upserted,
    'rows_deleted', v_deleted
  );
end;
$$;




